### PR TITLE
fix module object has no attribute NodeDef for tensorflow 0.11

### PR DESCRIPTION
**Pull request by qingzew**
reference  https://github.com/tensorflow/tensorflow/issues/4759

### CODE REVIEW

**Comment by qingzew** [comment]
I have signed it

**Comment by drpngx** [comment]
I think you need to have an exclamation mark, like so: I signed it!

**Comment by qingzew** [comment]
I signed it!

**Comment by drpngx** [comment]
The bot says that you need to login and sign on the web site.

**Comment by qingzew** [comment]
In fact I signed cla, and I think I set email locally in `tensorflow/models`, so I will close this one, and reopen laterly

**Pull request closed without merging**
