### PR TITLE
fix translate relevant import problem when used as lib.

### PR DESCRIPTION
**Pull request by cxxgtxy**

### CODE REVIEW

**Comment by cxxgtxy** [comment]
i signed it!

**Comment by nealwu** [comment]
@cxxgtxy Can you explain what problem you're trying to solve here?

**Comment by cxxgtxy** [comment]
Since the models github is popular now, many new published book cite the
modes for example. Tensorflow machine learning cookbook() is such a book(
https://github.com/nfmcclure/tensorflow_cookbook.git).
However when seq2seq_model needs imported, for example

 from models.tutorials.rnn.translate import seq2seq_model

Traceback (most recent call last):
  File
"/home/cxx/workspace/pythonApp/tensorflow_cookbook_cxx/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/05_seq2seq_translation.py",
line 25, in <module>
    from models.tutorials.rnn.translate import seq2seq_model
  File
"/home/cxx/workspace/virtualenvdir/tf3/lib/python3.5/site-packages/models/tutorials/rnn/translate/__init__.py",
line 21, in <module>
    import data_utils
ImportError: No module named 'data_utils'
NameError: name 'data_utils' is not defined
    Absolute import is recommended for python now, especially for python3.
 so


from . import data_utils
from . import seq2seq_model

is better
than

import data_utils
import seq2seq_model


2017-04-06 7:53 GMT+08:00 Neal Wu <notifications@github.com>:

**Comment by nealwu** [comment]
Thanks!

**Pull request merged**
