### PR TITLE
Modified tf.concat and tf.split argument order to get in line with tf…

### PR DESCRIPTION
**Pull request by paulskeie**
… 1.0

### CODE REVIEW

**Comment by paulskeie** [comment]
There are some more modifications need as well to make the code work in tf 1.0.  These are in lstm_ops.py. Perhaps @chfinn would like to make them herself.  tf.pack is not there anymore and I think the tf.zeros_initializer might have changed its API too.

**Comment by pobingwanghai** [comment]
@paulskeie I have just tested the video_prediction tutorial under tf1.0 version, it works fine, if you need to run the tutorial right now, you can see it in the new pull request. The only problem still remaining is the logging.flush(), but it can be ignored.

**Comment by cbfinn** [comment]
LGTM, though looks like there are some conflicts that need to be resolved.

**Comment by cbfinn** [comment]
Nevermind, it looks like the code was updated to 1.0 automatically using a script. I suppose we can close this PR now.

**Comment by nealwu** [comment]
Thanks! This should be covered by https://github.com/tensorflow/models/pull/1063, so I'm going to close. If there's anything that isn't covered, let me know.

**Pull request closed without merging**
