### PR TITLE
DeepLab: Fix generation of tfrecord for Cityscapes

### PR DESCRIPTION
**Pull request by ruslo**
# Description

Fix generation of tfrecord for Cityscapes and update documentation to use the correct split `--train_split="train_fine"`/`--eval_split="val_fine"`.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Tests

```
python deeplab/train.py \
    --logtostderr \
    --training_number_of_steps=100 \
    --train_split="train_fine" \
    --model_variant="xception_65" \
    --fine_tune_batch_norm=False \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --train_crop_size="769,769" \
    --train_batch_size=1 \
    --dataset="cityscapes" \
    --tf_initial_checkpoint=${PATH_TO_INITIAL_CHECKPOINT} \
    --train_logdir=${PATH_TO_TRAIN_DIR} \
    --dataset_dir=${PATH_TO_DATASET}
```

```
python deeplab/eval.py \
    --logtostderr \
    --eval_split="val_fine" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --eval_crop_size="1025,2049" \
    --dataset="cityscapes" \
    --max_number_of_evaluations=1 \
    --checkpoint_dir=${PATH_TO_CHECKPOINT} \
    --eval_logdir=${PATH_TO_EVAL_DIR} \
    --dataset_dir=${PATH_TO_DATASET}
```

```
python deeplab/vis.py \
    --logtostderr \
    --vis_split="val_fine" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --vis_crop_size="1025,2049" \
    --dataset="cityscapes" \
    --max_number_of_iterations=1 \
    --colormap_type="cityscapes" \
    --checkpoint_dir=${PATH_TO_CHECKPOINT} \
    --vis_logdir=${PATH_TO_VIS_DIR} \
    --dataset_dir=${PATH_TO_DATASET}
```

- Ubuntu 18.04.4
- CUDA 10.2
- Tensorflow 1.15.2

## Checklist

- [x] I have signed the [Contributor License Agreement](https://github.com/tensorflow/models/wiki/Contributor-License-Agreements).
- [x] I have read [guidelines for pull request](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).
- [x] My code follows the [coding guidelines](https://github.com/tensorflow/models/wiki/Coding-guidelines).
- [x] I have performed a self [code review](https://github.com/tensorflow/models/wiki/Code-review) of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by ruslo** [comment]
> Thanks, ruslo!

👌 

@aquariusjay Can you please review/merge the https://github.com/tensorflow/models/pull/8534 too

**Comment by aquariusjay** [comment]
Hi ruslo,

Thanks for the changes.
I just notice one thing that we could make the code better. Could you please have another pull request for the following changes?

1. Update the line in the main function:
for dataset_split in ['train', 'val']:
to
for dataset_split in ['train_fine', 'val_fine']:

2. Revert back your change in this line:
shard_filename = '%s_fine-%05d-of-%05d.tfrecord'
to
hard_filename = '%s-%05d-of-%05d.tfrecord' % (

By doing so, it will be more consistent with the renaming splits changes you have.

What do you think?

Thanks!

**Comment by ruslo** [comment]
> I just notice one thing that we could make the code better. Could you please have another pull request for the following changes?

Ok, I'll check it and test it tomorrow.

**Comment by aquariusjay** [comment]
Great! Thanks, ruslo!

**Comment by ruslo** [comment]
> Could you please have another pull request for the following changes?

@aquariusjay See https://github.com/tensorflow/models/pull/8870

**Comment by aquariusjay** [comment]
Checking it. Thanks, ruslo!

**Pull request merged**
