### PR TITLE
Removed preprocess function

### PR DESCRIPTION
**Pull request by yashk2810**
Removed the preprocess function which just performed division. @MarkDaoust

### CODE REVIEW

**Comment by yashk2810** [comment]
I signed it

**Comment by yashk2810** [comment]
I signed it

**Comment by yashk2810** [comment]
I signed it

**Comment by yashk2810** [comment]
I signed it

**Comment by yashk2810** [comment]
I signed it!

**Comment by yashk2810** [comment]
I signed it

**Comment by yashk2810** [comment]
I signed it!

**Comment by yashk2810** [comment]
I signed it

**Comment by msamogh** [comment]
I still think it's a good idea to have the `preprocess` function because it solidifies it as an important step in the training pipeline in the mind of a beginner (who is the intended audience).

**Comment by yashk2810** [comment]
I signed it

**Comment by lamberta** [comment]
Please include staging/preview link to your commit in comments: https://colab.sandbox.google.com/github/yashk2810/models/blob/master/samples/core/get_started/basic_classification.ipynb

**Comment by yashk2810** [comment]
I signed it

**Comment by yashk2810** [comment]
I signed it!

**Comment by yashk2810** [comment]
I signed it!

**Comment by MarkDaoust** [comment]
Hi @yashk2810,  

I'm not sure what's up with the cla thing. See: http://goto.google.com/cla#googlers

**Comment by yashk2810** [comment]
@MarkDaoust It doesn't make sense to have a separate function just for division. BTW we have different examples that show preprocessing of data

**Pull request closed without merging**
