### PR TITLE
from six.moves import xrange (en masse)

### PR DESCRIPTION
**Pull request by cclauss**
@nealwu As requested at https://github.com/tensorflow/models/issues/3103#issuecomment-356150374

For all files that use the Python 2-only builtin function __xrange()__, add the line __from six.moves import xrange__ for compatibility with Python 3.

### CODE REVIEW

**Comment by panyx0718** [comment]
The xrange is imported by not used? Would this cause lint issue?

**Comment by cclauss** [comment]
In which file is __xrange()__ not used?

**Comment by panyx0718** [comment]
I was looking at the diff. They import xrange. But I don't see xrange is used in the diff. I assume they weren't used before, otherwise there would be exceptions before this change.

**Comment by cclauss** [comment]
Each file contains at least one call to __xrange()__.  You can test this via:
```
python3 -m flake8 . --select=F821 | grep xrange
```

**Comment by panyx0718** [comment]
Oh, I see. you changed the existing xrange to use the six xrange

**Comment by nealwu** [comment]
Looks good @cclauss. Thanks!

**Pull request merged**
