### PR TITLE
Tutorials should be Python 3 compatible

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
Given the lack of response to #2105 , I have been reluctant to use `six`.

In this instance, we are __merely counting to 4__ so there is no significant difference between xrange() and range() so I elected to move to the new formulation.

**Comment by tfboyd** [comment]
Keep in mind in models there is no single owner so that make it very hard to fix anything in mass.  Soon there will be some changes to models where models that are very supported will be on one section and "other" stuff in another area.  I do not have a python3 environment to test in, a lame excuse but time is time.  I will try to do a quick test of your PR and merge it in as I do want our example to work on Python 3.  Thank you for your patience.

**Comment by tfboyd** [comment]
Yeah I am not allowed to run docker for security reasons.  but I can get
around that. Good idea.  I should have thought of it.  Thanks.  I should
get some rest.

**Comment by tfboyd** [comment]
The example is using six for other things so that will be fine for the example.  When they create the maintained area they can determine the guidelines.  I am going to keep this open but I will likely not merge it as we did a big refactor (more than we should have in one PR) to make the example also work with CloudML and some other nice features.  Part of this example is also to work with the high level API team to reduce boilerplate and move and improve code while moving it from contrib to core.  

Also thank you again for pointing out this issue.

**Comment by cclauss** [comment]
If your team is pressed for time then you should implement automated testing (#1980 or something similar) on PRs so that submissions that break things are automatically flagged.  This repo is now just a few PRs (#1981, #2109, #2116) away from having a passing flake8 score on Python 2.  We will get there.

**Comment by cclauss** [comment]
@tfboyd How is the review process going on this change?

**Pull request closed without merging**
