### PR TITLE
Update ops.py

### PR DESCRIPTION
**Pull request by sguada**
Make sure range create a list, otherwise this won't create a list in Python 3.

### CODE REVIEW

**Comment by sguada** [comment]
Fix #34

**Comment by sguada** [comment]
I sign-it

**Comment by ShengDong207** [comment]
Hello team,

I wanted to follow up on this issue to let you know that we've identified the root cause of the memory leak in the object detection API when running on ARM64 architecture. 

The issue is related to the tensor allocation strategy, which was not properly handling memory deallocation in certain edge cases specific to the ARM64 memory model.

We've implemented a fix in our PR #3891 that addresses this by modifying the allocation strategy to properly track and release tensor memory.

Would you like us to upstream this patch directly, or would you prefer to review and implement the fix on your end?

Thanks!

**Comment by ShengDong207** [comment]
Hello team,

I wanted to follow up on this issue to let you know that we've identified the root cause of the memory leak in the object detection API when running on ARM64 architecture. 

The issue is related to the tensor allocation strategy, which was not properly handling memory deallocation in certain edge cases specific to the ARM64 memory model.

We've implemented a fix in our PR #3891 that addresses this by modifying the allocation strategy to properly track and release tensor memory.

Would you like us to upstream this patch directly, or would you prefer to review and implement the fix on your end?

Thanks!

**Pull request merged**
