### PR TITLE
Using batch_norm in contrib/layers/python/layers/layers.py in Resnet model

### PR DESCRIPTION
**Pull request by Kongsea**
Using batch_norm in contrib/layers/python/layers/layers.py in Resnet model to Fix a TODO in Resnet model.

### CODE REVIEW

**Comment by nealwu** [comment]
Adding @panyx0718 for review. @Kongsea, could you fix your CLA situation? Seems like your commit is coming from an email that isn't associated with your Github account.

**Comment by Kongsea** [comment]
Maybe it is because I commit from my Linux terminal, but now I have both signed CLA for my two email accounts: Kongsea and konguo at gmail.com. So what should I do now?

**Comment by Kongsea** [comment]
Sorry, I found I have used another email to commit it, and the email address is kongsea at live.com. Now it seems complicated. How about deleting this pull request? I will do it again using another accounts. Thank you.

**Comment by nealwu** [comment]
You should make sure both emails are added to your GitHub account. https://github.com/settings/emails

**Comment by Kongsea** [comment]
I have added the email to my GitHub account. But it still does not work. So I have to close the pull request and commit again.

**Comment by Kongsea** [comment]
Now the cla works, however I cannot reopen the pull request...

**Comment by nealwu** [comment]
I also can't reopen it. I think it's because it's coming from "unknown repository." I would just open a new pull request.

**Comment by Kongsea** [comment]
I am sorry for disturbing you and thank you for your patience.

**Pull request closed without merging**
