### PR TITLE
Look for Python syntax errors when testing

### PR DESCRIPTION
**Pull request by cclauss**
http://flake8.readthedocs.io/en/latest/user/error-codes.html#error-violation-codes says:
* _We report __E999__ when we fail to compile a file into an Abstract Syntax Tree_...

### CODE REVIEW

**Comment by nealwu** [comment]
@av8ramit is this something we should add?

**Comment by nealwu** [comment]
Jenkins, test this please.

**Comment by karmel** [comment]
I think this will just print errors into the Jenkins logs. Is the intent to fail on flake failure?

**Comment by av8ramit** [comment]
@nealwu up to you guys

**Comment by karmel** [comment]
@cclauss can you clarify what exactly the intent is here? As I understand this, this runs flake for the whole repo (for each iteration in the loop, by the way), but just for one particular error related to ASTs? Is there a particular reason to want to test AST parsing?

**Comment by cclauss** [comment]
The intent it to:
1. pip install flake8
2. run one flake8 test () on all Python files in the repo.
3. if there a Python Syntax Error is found then fail the build warning the user on the way out

AST parsing let's us find the syntax errors which used to be a problem (#2946) and we would like to avoid regressions.  My personal cocktails is --select=E901,E999,F821,F822,F823 but I decided to be conservative given the reluctance to do public testing.  F821 (undefined names) is really helpful at [spotting typos, bugs, and Py2/3 incompatibilities](https://github.com/tensorflow/models/issues?q=is%3Apr+author%3Acclauss+is%3Aclosed).

**Comment by pkulzc** [comment]
Pull request #3380 already contains these change.

**Comment by cclauss** [comment]
@pkulzc #3380 was a great PR to have merged.  However it did not add the tests that this PR is attempting to add.

**Comment by karmel** [comment]
Testing has been moved to other systems in #3504 ; closing this as a result. Thanks for keeping an eye out, @cclauss

**Pull request closed without merging**
