### PR TITLE
Update with tf-estimator-nightly

### PR DESCRIPTION
**Pull request by saberkun**

### CODE REVIEW

**Comment by saberkun** [comment]
Not working...

**Comment by tfboyd** [comment]
estimator is being installed when tf is installed it does not need to be installed by itself.  Unless I am missing something and maybe I am.  I have estimator tests and they all pass TF 1.0 and TF 2.0.  Here is the pip freeze after the docker is created and the docker does not install tf-estimator directly.  If running TF 1.0 you would not get 2.0 preview.

https://sponge.corp.google.com/target?id=e3fb045c-ab7c-4f78-94d7-1aa668259fb7&target=tensorflow_models%2Fperfzero%2Faccuracy%2Fv100_1_gpu%2Fresnet56_estimator_v2&searchFor=

2019-08-07 11:01:33,786 DEBUG: Step 20/20 : RUN pip freeze

2019-08-07 11:01:33,842 DEBUG:  ---> Running in a3ffc9d35e31

2019-08-07 11:01:34,677 DEBUG: absl-py==0.7.1

2019-08-07 11:01:34,677 DEBUG: astor==0.8.0

2019-08-07 11:01:34,677 DEBUG: attrs==19.1.0

2019-08-07 11:01:34,677 DEBUG: cachetools==3.1.1

2019-08-07 11:01:34,677 DEBUG: certifi==2019.6.16

2019-08-07 11:01:34,678 DEBUG: chardet==3.0.4

2019-08-07 11:01:34,678 DEBUG: dill==0.3.0

2019-08-07 11:01:34,678 DEBUG: future==0.17.1

2019-08-07 11:01:34,678 DEBUG: gast==0.2.2

2019-08-07 11:01:34,678 DEBUG: google-api-core==1.14.2

2019-08-07 11:01:34,678 DEBUG: google-api-python-client==1.7.10

2019-08-07 11:01:34,678 DEBUG: google-auth==1.6.3

2019-08-07 11:01:34,678 DEBUG: google-auth-httplib2==0.0.3

2019-08-07 11:01:34,678 DEBUG: google-cloud==0.34.0

2019-08-07 11:01:34,678 DEBUG: google-cloud-bigquery==1.17.0

2019-08-07 11:01:34,678 DEBUG: google-cloud-core==1.0.3

2019-08-07 11:01:34,678 DEBUG: google-pasta==0.1.7

2019-08-07 11:01:34,678 DEBUG: google-resumable-media==0.3.2

2019-08-07 11:01:34,678 DEBUG: googleapis-common-protos==1.6.0

2019-08-07 11:01:34,678 DEBUG: grpcio==1.22.0

2019-08-07 11:01:34,678 DEBUG: h5py==2.9.0

2019-08-07 11:01:34,678 DEBUG: httplib2==0.13.1

2019-08-07 11:01:34,678 DEBUG: idna==2.8

2019-08-07 11:01:34,678 DEBUG: joblib==0.13.2

2019-08-07 11:01:34,678 DEBUG: kaggle==1.5.5

2019-08-07 11:01:34,678 DEBUG: Keras-Applications==1.0.8

2019-08-07 11:01:34,678 DEBUG: Keras-Preprocessing==1.1.0

2019-08-07 11:01:34,678 DEBUG: Markdown==3.1.1

2019-08-07 11:01:34,678 DEBUG: mlperf-compliance==0.0.10

2019-08-07 11:01:34,678 DEBUG: mock==3.0.5

2019-08-07 11:01:34,678 DEBUG: numpy==1.17.0

2019-08-07 11:01:34,678 DEBUG: oauth2client==4.1.3

2019-08-07 11:01:34,679 DEBUG: opt-einsum==2.3.2

2019-08-07 11:01:34,679 DEBUG: pandas==0.25.0

2019-08-07 11:01:34,679 DEBUG: promise==2.2.1

2019-08-07 11:01:34,679 DEBUG: protobuf==3.9.1

2019-08-07 11:01:34,679 DEBUG: psutil==5.6.3

2019-08-07 11:01:34,679 DEBUG: py-cpuinfo==5.0.0

2019-08-07 11:01:34,679 DEBUG: pyasn1==0.4.6

2019-08-07 11:01:34,679 DEBUG: pyasn1-modules==0.2.6

2019-08-07 11:01:34,679 DEBUG: pygobject==3.26.1

2019-08-07 11:01:34,679 DEBUG: python-apt==1.6.4

2019-08-07 11:01:34,679 DEBUG: python-dateutil==2.8.0

2019-08-07 11:01:34,679 DEBUG: python-slugify==3.0.3

2019-08-07 11:01:34,679 DEBUG: pytz==2019.2

2019-08-07 11:01:34,679 DEBUG: PyYAML==5.1.2

2019-08-07 11:01:34,679 DEBUG: requests==2.22.0

2019-08-07 11:01:34,679 DEBUG: rsa==4.0

2019-08-07 11:01:34,679 DEBUG: scikit-learn==0.21.3

2019-08-07 11:01:34,679 DEBUG: scipy==1.3.0

2019-08-07 11:01:34,679 DEBUG: six==1.12.0

2019-08-07 11:01:34,679 DEBUG: tb-nightly==1.15.0a20190806

2019-08-07 11:01:34,679 DEBUG: tensorflow-estimator-2.0-preview==1.14.0.dev2019080700

2019-08-07 11:01:34,679 DEBUG: tensorflow-metadata==0.14.0

2019-08-07 11:01:34,679 DEBUG: termcolor==1.1.0

2019-08-07 11:01:34,679 DEBUG: text-unidecode==1.2

2019-08-07 11:01:34,679 DEBUG: tf-nightly-gpu-2.0-preview==2.0.0.dev20190807

2019-08-07 11:01:34,680 DEBUG: tfds-nightly==1.1.0.dev201908070105

2019-08-07 11:01:34,680 DEBUG: tqdm==4.32.2

2019-08-07 11:01:34,680 DEBUG: typing==3.7.4

2019-08-07 11:01:34,680 DEBUG: uritemplate==3.0.0

2019-08-07 11:01:34,680 DEBUG: urllib3==1.24.3

2019-08-07 11:01:34,680 DEBUG: Werkzeug==0.15.5

2019-08-07 11:01:34,680 DEBUG: wrapt==1.11.2

2019-08-07 11:01:35,132 DEBUG: Removing intermediate container a3ffc9d35e31

2019-08-07 11:01:35,132 DEBUG:  ---> 7e24f850aedb

2019-08-07 11:01:35,132 DEBUG: Successfully built 7e24f850aedb

2019-08-07 11:01:35,137 DEBUG: Successfully tagged perfzero/tensorflow:latest

**Comment by saberkun** [comment]
Thanks, Toby. Yes, you are right that estimator is already installed inside tf-nightly.
Then, how to fix: https://sponge.corp.google.com/target?id=cc7004bb-1a0b-4e58-b698-56d0d5f4e043&target=tensorflow_models%2Fubuntu%2Fpy3%2Fpresubmit_gpu_v2&searchFor=
Ubuntu Python3 are failing. Do you know what's the reason?

**Comment by saberkun** [comment]
Do you mean we only need to care: Ubuntu GPU Python3 TF 2.x?
Ubuntu Python3 is expected to fail

**Comment by tfboyd** [comment]
It is a great question.  I removed the TF 1.0 py2 presubmit for the same reason and because I thought debugging it was silly.  I would suggest removing the py3 presubmit and then we add at CPU presubmit that matches my TF 2.0 GPU presubmit that uses docker.  

I am perplexed as to why this started failing but given all the work we have to do it seems like a waste of time to figure it out when if someone was using TF 1.0 they should go back to the TF 1.14 tag/branch or we tag it back at the last time the test pass.  I trust my benchmarks runs more anyway and they are still passing.  

I would have already made a TF 2.0 CPU presubmit, but the situation is complicated.  It has nothing to do with you, Jing, or anyone at your level.  I like the docker containers because they are easier to debug and if I want a new library I just update the docker vs. having to make a new image.  There are pros and cons.  It also is the same image we use for benchmarking so there is continuity.  

Thank you for trying to fix it.  I can rip out the py3 TF 1.0 tests pretty fast tomorrow.  My confidence is higher after removing the py2 tests.

**Comment by saberkun** [comment]
Thank you for explanation, Toby.
Sounds good. I saw the most of test errors are from estimator module is missing.

**Pull request closed without merging**
