### PR TITLE
Updates official NCF with TC-optimized changes

### PR DESCRIPTION
**Pull request by tayo**
This PR attempts to integrate the TPU-TC Estimator implementation with the main version.

Changes that should be discussed in particular:
- The eval_pred_fn creation occurs in every loop iteration.  Can this be pulled out of the loop?
- The calculation of num_train_steps was previously called 'approx_train_steps' and was slightly diffferent.  One version wraps the equation in a ceil() and the other does not.  Correctness should be confirmed.

### CODE REVIEW

**Comment by tayo** [comment]
Please add robieta@ as a reviewer.

**Comment by robieta** [comment]
Lovely. Thanks for bringing these optimizations back to open source. To provide some context on your concerns.

1) The reason for the somewhat curious placement of the eval input function creation is to spend less time waiting. The async process first generates the first epoch of training data, then the eval data, and then subsequent epochs. And because the main thread will block on input_fn creation waiting for data, we want the eval input_fn to be created after the first epoch of training. However it will only be created once, and then reused.

2) Previously, the last partial batch of an epoch would spill over into the next epoch. This meant that every few epochs there would be an extra batch. That mechanism has been removed and training now randomly resamples the epoch for points with which to pad. This means that the number of training batches per epoch is now constant.

Hope that helps.

**Comment by tayo** [comment]
That all makes sense, thanks.

**Comment by robieta** [comment]
Overall this looks fine. Once https://github.com/tensorflow/models/pull/5623 lands you should rebase to that (or whatever you preferred git workflow is). The interactions between that and this PR should be pretty minor.

P.S. Because of the way that Kokoro works, any merge conflict means that you auto-fail tests without running them. (That's why they're broken.)

**Comment by tayo** [comment]
Chatted with reedwm@ offline.  Seems like the diff history of this branch has been lost somehow, as the PR currently includes both commits.  I will extract the diff and re-apply it to a clean master.

**Comment by tayo** [comment]
Closing this pull request. Will send a fresh one with the correct diff.

**Pull request closed without merging**
