### PR TITLE
Use new mixed_float16 policy for resnet.

### PR DESCRIPTION
**Pull request by reedwm**
The old infer_float32_policies policy will be removed from TensorFlow soon.

To test convergence, I ran the Resnet50KerasAccuracy.benchmark_8_gpu_fp16 benchmark. I got an accuracy of 0.76037 and an exp_per_second of 6908.

### CODE REVIEW

**Comment by saberkun** [comment]
Tests failed?

**Comment by saberkun** [comment]
Can we disable no-name-in-module or other wrong errors inside pylint.rc?

**Comment by reedwm** [comment]
I don't think the test failures are caused by this PR.

I'm not sure how to disable lint errors inside pylint.rc. I can figure it out in a future PR.

**Comment by saberkun** [comment]
I don't see these tests are failing internally. Either it is the issue with docker or the changes

**Comment by reedwm** [comment]
Hmmm, looks like the test failures are caused by this PR?

Any ideas how to debug this? I cannot reproduce locally, and the error does not seem related to fp16 at all.

**Pull request closed without merging**
