### PR TITLE
Slim generic dataset

### PR DESCRIPTION
**Pull request by look4pritam**
Creates TFRecord files for training and validation for any generic dataset using following command.

python download_and_convert_data.py --dataset_name=generic --dataset_dir=/dataset/tensorflow/flowers/ --source_dir=/dataset/flowers/
 
Here in this example  
--source_dir contains flowers dataset but any other dataset can be input.

Then train for given dataset using following command.

python train_image_classifier.py --train_dir=/workspace/models/generic --dataset_name=generic --dataset_split_name=train --dataset_dir=/dataset/tensorflow/flowers --model_name=inception_v3 --save_interval_secs=600 --save_summaries_secs=120 --log_every_n_steps=50 --max_number_of_steps=200

Finally evaluate using following command.

python eval_image_classifier.py --checkpoint_path=/workspace/models/generic --eval_dir=/workspace/models/generic --dataset_name=generic --dataset_split_name=validation --dataset_dir=/dataset/tensorflow/flowers --model_name=inception_v3

### CODE REVIEW

**Comment by look4pritam** [comment]
I have signed it!

**Comment by rishirai10** [comment]
I signed it!

**Comment by look4pritam** [comment]
It is signed.

**Comment by rishirai10** [comment]
I signed it!

**Pull request closed without merging**
