### PR TITLE
Update object_detection_evaluation.py for some fixes relating to issue #5924

### PR DESCRIPTION
**Pull request by yaceben**
fixed unicode category_name for compatibility with python 3.x
fixed bug where `groundtruth_dict[standard_fields.InputDataFields.groundtruth_group_of]` of NoneType would throw an error in the if statement

### CODE REVIEW

**Comment by yaceben** [comment]
I signed it!

**Comment by yaceben** [comment]
Thanks @manolosolalinde! 

Cheers

**Comment by yaceben** [comment]
ping @derekjchow, @dreamdragon, @jch1, @pkulzc

**Comment by jaeyounkim** [comment]
@tombstone Please review this pull request.

**Comment by saberkun** [comment]
This pr is stale.

**Pull request closed without merging**
