### PR TITLE
Convert slim models to TF1.0

### PR DESCRIPTION
**Pull request by javiribera**
TF1.0 has breaking changes like tf.concat
(https://www.tensorflow.org/install/migration)
I just applied the script in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility
to this directory.

### CODE REVIEW

**Comment by MarvinTeichmann** [comment]
The patch does not seem to update the entire source code. Using your repository I tried training vgg model on cifar10 data using:

> python train_image_classifier.py --train_dir=$SLIM_TRAIN_DIR --dataset_dir=$SLIM_DATA_DIR --dataset_split_name=train --model_name=vgg_16 --dataset_name=cifar10

This produces the following error message:

```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 448, in main
    image = image_preprocessing_fn(image, train_image_size, train_image_size)
  File "/home/mifs/mttt2/github/tf-models/slim/preprocessing/preprocessing_factory.py", line 70, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
  File "/home/mifs/mttt2/github/tf-models/slim/preprocessing/vgg_preprocessing.py", line 367, in preprocess_image
    resize_side_min, resize_side_max)
  File "/home/mifs/mttt2/github/tf-models/slim/preprocessing/vgg_preprocessing.py", line 317, in preprocess_for_train
    image = _random_crop([image], output_height, output_width)[0]
  File "/home/mifs/mttt2/github/tf-models/slim/preprocessing/vgg_preprocessing.py", line 175, in _random_crop
    crop_height, crop_width) for image in image_list]
  File "/home/mifs/mttt2/github/tf-models/slim/preprocessing/vgg_preprocessing.py", line 76, in _crop
    tf.pack([crop_height, crop_width, original_shape[2]]))
AttributeError: 'module' object has no attribute 'pack'
```

Did you apply `tf_upgrade` also to `preprocessing` ?

**Comment by javiribera** [comment]
@MarvinTeichmann, no. I only applied `tf_upgrade` to  `slim/nets`.
The file you are running [`vgg_preprocessing.py`](https://github.com/tensorflow/models/blob/master/slim/preprocessing/vgg_preprocessing.py#L76) seems to be still using TF0.12.
From [here](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#breaking-changes-to-the-api), _tf.pack and tf.unpack are deprecated in favor of tf.stack and tf.unstack_

I'm afraid a lot of other code in this repo is also broken after upgrading to TF1.0.

**Comment by MarvinTeichmann** [comment]
Hi javiri,
have you seen, that there is now an a slim version included in [tensorflow](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim). This contains version of the models compatible with tf1.0. I have switched to use this code as the code in here seams to be unsupported by now.

**Comment by javiribera** [comment]
@MarvinTeichmann true, but as far as I know, the models are kept in this repository (inception_v4 is not in the tensorflow repo). It would be great some official policy on this matter.
Also, #1053 seems to be a superset of this pull request.

**Comment by MarvinTeichmann** [comment]
You are right, inception_v4 is only in here. Most other models are also over there and some of the content in tensorflow is newer. An official repository policy would be good.

**Comment by nealwu** [comment]
Thanks! This should be covered by https://github.com/tensorflow/models/pull/1063 and https://github.com/tensorflow/models/pull/1053, so I'm going to close. If there's anything that isn't covered, let me know.

**Pull request closed without merging**
