### PR TITLE
Fix fp16 Transformer model.

### PR DESCRIPTION
**Pull request by reedwm**
Also, do Transformer inference in fp16, as well as training, when --dtype=fp16. In TF 2, layers now cannot run in multiple different dtypes, so we must use the same dtype for training and inference.

### CODE REVIEW

**Comment by tfboyd** [comment]
@reedwm does this fix the overall issue with Transformer and FP16.  I would like to do an end-to-end run with this PR before we accept.  I feel odd accepting this when all FP16 is broken currently for Transformer.  Open to a dialog to move this forward.

**Comment by reedwm** [comment]
Yes, this fixes the overall issue with Transformer and fp16. In order to fix it, I had to do inference in fp16 as well, but it should all work.

I can start off an end-to-end run

**Comment by tfboyd** [comment]
Presubmit passing is nice.  Please check lint, that check has been greatly improved.  Has a few quirks still but mostly better.

**Comment by reedwm** [comment]
Not sure why I'm failing lint or presubmit. For lint, it claims some classes aren't callable when they are. Presubmit shows me failing unrelated tests.

How do I rerun the lint and presubmit?

**Comment by tfboyd** [comment]
@reedwm  I was saying presubmit is finally passing with the FP16 fixes.  The TF 1.0 presubmit will be removed soon.  I already removed one of them.  You can try to trigger the lint again with `kokoro: force-run` I already added it.

**Comment by tfboyd** [comment]
We may want to as @saberkun if he can turn off some of the lint checks that do not seem to be accurate.  I had a non-callable situation as well and I ended up ignoring it.  His approach is the right way; we may just need some tweaks to the rules or the environment where the checks take place.  If this happens again just make a comment, you don't need to add the disable, the lint only checks the parts you update (or is supposed to limit it to that) vs. the old lint check which made you pay for everyone else that was sloppy.

**Comment by reedwm** [comment]
Running the model with this PR, the beak uncased BLEU score was 28.235626220703125 at the end of epoch 7.

**Pull request merged**
