### PR TITLE
Object detection: Run evalutation in CPU and run evaluation on all checkpoints

### PR DESCRIPTION
**Pull request by Abhijit-2592**
This is a small additional feature which will be helpful  for people with **single GPU (gtx-1060, gtx-1080 etc)** or **limited GPU memory.**

If above is the case, when both the Training and evaluation scripts are started together (official recommended way), training might hang or might cause Resource Exhaust Error! (Especially with Faster RCNN architecture). In most cases the user experiences training freeze because, The evaluation script will take over the hardware, creating a training bottleneck.There are two ways to go about this problem.

1. Run training in GPU and run evaluation in CPU. (even this solution does not guarantee that your training will work without freezing if you have RAM less than 16GB or you use a heavy model).

2. Run only training script for specific iterations and then run the evaluation script, to check if the model has converged. I know this is a round about way but, I couldn't think of any better solution .Before this commit, evaluation script runs evaluation only on the latest checkpoint thus, you won't be able to evaluate other checkpoints. This commit also addresses this problem by optionally making it to run on all the checkpoints

Both of the above cases can be set using boolean via terminal while calling eval.py script

### CODE REVIEW

**Comment by Abhijit-2592** [comment]
I signed it!

**Comment by GustavZ** [comment]
very nice work!

**Comment by Abhijit-2592** [comment]
@GustavZ glad it helped you😁

**Comment by GustavZ** [comment]
@Abhijit-2592 I tried the option to evaluate all checkpoints for the first time and it gives me this error.
```
Traceback (most recent call last):
  File "/home/gustav/workspace/tensorflow/tf_models/research/object_detection/eval.py", line 142, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/gustav/workspace/tensorflow/tf_models/research/object_detection/eval.py", line 138, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir, FLAGS.evaluate_all_checkpoints)
  File "/home/gustav/workspace/tensorflow/tf_models/research/object_detection/evaluator.py", line 281, in evaluate
    losses_dict=losses_dict)
  File "/home/gustav/workspace/tensorflow/tf_models/research/object_detection/eval_util.py", line 502, in repeated_checkpoint_run
    losses_dict=losses_dict)
  File "/home/gustav/workspace/tensorflow/tf_models/research/object_detection/eval_util.py", line 339, in _run_checkpoint_once
    restore_fn(sess)
TypeError: _restore_specific_checkpoint() takes exactly 2 arguments (1 given)
/home/gustav/workspace/tensorflow/tf_models/research/object_detection/utils/visualization_utils.py:25: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
 
I try to hunt it down my self
```

**Comment by Abhijit-2592** [comment]
@GustavZ I will take a look at it

**Comment by GustavZ** [comment]
@Abhijit-2592 i found it. 
You forgot to pass `evaluate_all_checkpoints=evaluate_all_checkpoints,` into  `metrics = eval_util.repeated_checkpoint_run()` in file `evaluator.py`

Have you been able to train on all checkpoints with this? seems impossible to me

**Comment by Abhijit-2592** [comment]
@GustavZ  Sorry my bad I copy pasted the code from my local machine (should have merged it using branches!), I local code I have has it, so it runs correctly, I forgot to edit it properly, will change it now should work

**Comment by GustavZ** [comment]
@Abhijit-2592 I am still not able to train on all checkpoints,  i see following error when enabling evaluation on all checkpoints:
```
/home/ubuntu/tf_models/research/object_detection/utils/metrics.py:142: RuntimeWarning: invalid value encountered in true_divide
  num_images_correctly_detected_per_class / num_gt_imgs_per_class)
/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:703: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)
Traceback (most recent call last):
  File "/home/ubuntu/tf_models/research/object_detection/eval.py", line 142, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/tf_models/research/object_detection/eval.py", line 138, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir, FLAGS.evaluate_all_checkpoints)
  File "/home/ubuntu/tf_models/research/object_detection/evaluator.py", line 283, in evaluate
    losses_dict=losses_dict)
  File "/home/ubuntu/tf_models/research/object_detection/eval_util.py", line 547, in repeated_checkpoint_run
    save_graph_dir)
  File "/home/ubuntu/tf_models/research/object_detection/eval_util.py", line 250, in _run_specific_checkpoint_once
    image_id=batch, groundtruth_dict=result_dict)
  File "/home/ubuntu/tf_models/research/object_detection/utils/object_detection_evaluation.py", line 193, in add_single_ground_truth_image_info
    groundtruth_dict[standard_fields.InputDataFields.groundtruth_classes] -
TypeError: tuple indices must be integers, not str

```

**Comment by Abhijit-2592** [comment]
I will look over this weekend.

**Comment by MrYoungblood** [comment]
@Abhijit-2592 Did you have a look on it? I am getting also the same error.

**Comment by Abhijit-2592** [comment]
@MrYoungblood  sorry man I haven't had time to look at it. Will look at this this weekend. Moreover the original code base has changed a lot leading to conflict. Give me a week and I will get back to you ASAP

**Comment by askozirev** [comment]
I have the same bug as @GustavZ. The solution that helped me: in research/object_detection/eval_util.py, in function `_run_specific_checkpoint_once` I replaced this line:
```
result_dict = batch_processor(tensor_dict, sess, batch, counters)
```
 to 
```
result_dict = batch_processor(tensor_dict, sess, batch, counters)[0]
```

**Comment by raudipra** [comment]
how do eval and training work? Do the gpu and cpu run in parallel?

**Comment by Abhijit-2592** [comment]
This is now redundant with the current version of the object detection API

**Pull request closed without merging**
