### PR TITLE
Fix bug in transformer model: Changed the examples to specify the output size

### PR DESCRIPTION
**Pull request by elezar**
Although the interface to the transformer was changed in #57, the examples were never updated.

I have made the changes for both the simple example and the cluttered MNIST examples.

### CODE REVIEW

**Comment by elezar** [comment]
I signed it!

**Comment by elezar** [comment]
@psycharo and @daviddao Could you have a look at the changes?

**Comment by psycharo** [comment]
Seems fine, thanks!

**Comment by elezar** [comment]
Thanks.

**Comment by elezar** [comment]
@martinwicke could you have a look at the change and merge the PR?

**Comment by martinwicke** [comment]
Thanks!

**Pull request merged**
