### PR TITLE
Fixed Open Images TF Record creation for Python 3

### PR DESCRIPTION
**Pull request by phmagic**

### CODE REVIEW

**Comment by phmagic** [comment]
I've signed the CLA, hopefully this fix will be helpful for people using the Open Images Dataset. This is my first PR so let me know how I can be most help.

**Comment by jaeyounkim** [comment]
I am closing this PR since the CLA has not been resolved.

**Comment by angrod01** [comment]
Glad I found this fix. Thanks! Don't know why it got closed

**Comment by jaeyounkim** [comment]
@angrod01 I had to close it because @phmagic did not sign the CLA.
If you submit a new pull request and sign the CLA, I will review it again to approve.

**Comment by jaeyounkim** [comment]
@phmagic I've checked our CLA system again, and I found the CLA you signed. Let me reopen this pull request for review.

**Pull request closed without merging**
