### PR TITLE
Update lm_1b_eval.py (Python 3 compatibility)

### PR DESCRIPTION
**Pull request by edouardfouche**
Solve Python 3 compatibility:
- replacing xrange to range
- add .decode() after f.read() to get strings instead of bytes when reading text file

### CODE REVIEW

**Comment by edouardfouche** [comment]
I signed it!

**Comment by nealwu** [comment]
Hi @edouardfouche, could you update this to use [six](https://pythonhosted.org/six/) in order to maintain compatibility with both Python 2 and Python 3?

**Comment by edouardfouche** [comment]
OK. It was already working for both actually (except that range creates a list instead of a generator in Python, which was not a big deal here), but I have replaced `range` by `six.moves.range` now.

**Comment by nealwu** [comment]
@panyx0718 does this look good to you?

**Comment by nealwu** [comment]
Great. Thanks @edouardfouche!

**Comment by nealwu** [comment]
(As a side note, the reason to use `six.moves.range` / `six.moves.xrange` rather than just `range` is that it will end up as `xrange` in Python 2, which has slightly better performance than `range`.)

**Comment by edouardfouche** [comment]
Yep. Thx @nealwu !

**Pull request merged**
