### PR TITLE
Release MobileDet code and model, and require tf_slim installation for OD API.

### PR DESCRIPTION
**Pull request by pkulzc**
# Description

Update models/slim to use tf_slim instead of contrib.slim, 

Release MobileDet code and model in Object Detection API.
tf_slim is now required to be installed for OD API.

## Type of change

For a new feature or function, please create an issue first to discuss it
with us before submitting a pull request.

Note: Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update
- [ ] TensorFlow 2 migration
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] A new research paper code implementation
- [ ] Other (Specify)

## Tests

> :memo: Please describe the tests that you ran to verify your changes.
>  
> * Provide instructions so we can reproduce.  
> * Please also list any relevant details for your test configuration.  

**Test Configuration**:

## Checklist

- [ ] I have signed the [Contributor License Agreement](https://github.com/tensorflow/models/wiki/Contributor-License-Agreements).
- [ ] I have read [guidelines for pull request](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).
- [ ] My code follows the [coding guidelines](https://github.com/tensorflow/models/wiki/Coding-guidelines).
- [ ] I have performed a self [code review](https://github.com/tensorflow/models/wiki/Code-review) of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by saberkun** [comment]
The external pylint is incremental, so merging this PR will not affect other files.

**Comment by spartako** [comment]
bipartite_matcher.py has a tensorflow.contrib import:
`from tensorflow.contrib.image.python.ops import image_ops`
This will fail on tf2 installs

**Comment by marksandler2** [comment]
@spartako 
> bipartite_matcher.py has a tensorflow.contrib import:
> `from tensorflow.contrib.image.python.ops import image_ops`
> This will fail on tf2 installs

Yes, it is not supposed to be a full elimination for tf.contrib (only tf.contrib.slim is eilminated)

**Comment by sguada** [comment]
There seems to be many failures in in the internal CI.

**Comment by pkulzc** [comment]
Thank you all!

**Comment by ramesh8v** [comment]
Hello,

with tf2 install, bipartite_matcher.py is producing an error.

`File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/home/ramesh8v/2tb/walnut_images/models/research/object_detection/model_lib.py", line 30, in <module>
    from object_detection import exporter as exporter_lib
  File "/home/ramesh8v/2tb/walnut_images/models/research/object_detection/exporter.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/home/ramesh8v/2tb/walnut_images/models/research/object_detection/builders/model_builder.py", line 25, in <module>
    from object_detection.builders import matcher_builder
  File "/home/ramesh8v/2tb/walnut_images/models/research/object_detection/builders/matcher_builder.py", line 19, in <module>
    from object_detection.matchers import bipartite_matcher
  File "/home/ramesh8v/2tb/walnut_images/models/research/object_detection/matchers/bipartite_matcher.py", line 20, in <module>
    from tensorflow.contrib.image.python.ops import image_ops
ModuleNotFoundError: No module named 'tensorflow.contrib'
`
Do I need to uninstall tf2 and tf1 to run object detection? I'd appreciate any help!

Thanks

**Pull request merged**
