### PR TITLE
Project import generated by Copybara.

### PR DESCRIPTION
**Pull request by joel-shor**
PiperOrigin-RevId: 176561168

Fix tensorflow/models/gan README internal links.

@nealwu

### CODE REVIEW

**Comment by nealwu** [comment]
Please also fix `Unconditional GAN{width="330"}`.

**Comment by joel-shor** [comment]
@nealwu Changed the widths of the images in the README.

**Comment by joel-shor** [comment]
Sorry for that! Images are actually added to github now. Corresponding internal change is cl/176626382.

**Comment by nealwu** [comment]
Nice! Looks good.

**Pull request merged**
