### PR TITLE
Update yamnet_visualization.ipynb to work under TF2.0.

### PR DESCRIPTION
**Pull request by dpwe**
Somehow explicitly setting a tensor flow graph context manager fixed the batch-size problem that appeared for tensorflow 2.0.

### CODE REVIEW

**Comment by rae89** [comment]
I am still getting this error when I run `python inference audio.wav` 

> Traceback (most recent call last):
  File "inference.py", line 64, in <module>
    main(sys.argv[1:])
  File "inference.py", line 52, in main
    scores, _ = yamnet.predict(np.reshape(waveform, [1, -1]), steps=1)
  File "/Users/respinoza/Projects/yamnet/yamnet/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "/Users/respinoza/Projects/yamnet/yamnet/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "/Users/respinoza/Projects/yamnet/yamnet/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 475, in _model_iteration
    total_epochs=1)
  File "/Users/respinoza/Projects/yamnet/yamnet/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 179, in run_one_epoch
    batch_end=step * batch_size + current_batch_size)
  File "/Users/respinoza/Projects/yamnet/yamnet/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 347, in aggregate
    result.aggregate(batch_element, batch_start, batch_end)
  File "/Users/respinoza/Projects/yamnet/yamnet/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 271, in aggregate
    batch_element.shape, self.results.shape))
ValueError: Mismatch between expected batch size and model output batch size. Output shape = (80, 521), expected output shape = shape (1, 521)

**Comment by dpwe** [comment]
Can you tell me the output of:

print(tf.__version__)

?

Thanks,

  DAn.

**Comment by rae89** [comment]
my pip freeze has this for tensorflow version:

```
tensorboard==2.1.0
tensorflow==2.1.0
tensorflow-estimator==2.1.0
```

**Comment by plakal** [comment]
Does the yamnet test work for you?  'python yamnet_test.py'.

If that works, then we might have to apply the same workaround to
inference.py as we did for the visualization notebook (force use of TF1
compat APIs and an explicit Graph).

**Comment by rae89** [comment]
Here is the output for `python yamnet_test.py`:

> Running tests under Python 3.7.2: /Users/respinoza/Projects/yamnet/yamnet/bin/python3
/Users/respinoza/Projects/yamnet/yamnet/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/data_structures.py:720: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(wrapped_dict, collections.Mapping):
WARNING:tensorflow:From /Users/respinoza/Projects/yamnet/yamnet/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0225 15:34:34.849059 4535731648 deprecation.py:506] From /Users/respinoza/Projects/yamnet/yamnet/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
[ RUN      ] YAMNetTest.testRandom
WARNING:tensorflow:When passing input data as arrays, do not specify `steps_per_epoch`/`steps` argument. Please use `batch_size` instead.
W0225 15:34:36.715025 4535731648 training_utils.py:1306] When passing input data as arrays, do not specify `steps_per_epoch`/`steps` argument. Please use `batch_size` instead.
[       OK ] YAMNetTest.testRandom
[ RUN      ] YAMNetTest.testSine
WARNING:tensorflow:When passing input data as arrays, do not specify `steps_per_epoch`/`steps` argument. Please use `batch_size` instead.
W0225 15:34:37.187715 4535731648 training_utils.py:1306] When passing input data as arrays, do not specify `steps_per_epoch`/`steps` argument. Please use `batch_size` instead.
[       OK ] YAMNetTest.testSine
[ RUN      ] YAMNetTest.testZeros
WARNING:tensorflow:When passing input data as arrays, do not specify `steps_per_epoch`/`steps` argument. Please use `batch_size` instead.
W0225 15:34:37.211072 4535731648 training_utils.py:1306] When passing input data as arrays, do not specify `steps_per_epoch`/`steps` argument. Please use `batch_size` instead.
[       OK ] YAMNetTest.testZeros
[ RUN      ] YAMNetTest.test_session
[  SKIPPED ] YAMNetTest.test_session
----------------------------------------------------------------------
Ran 4 tests in 2.922s

OK (skipped=1)

**Comment by plakal** [comment]
The yamnet test passes for you so that confirms that we should use an
explicit tf.Graph() in inference.py as well, for now, until we do a more
proper TF2-style conversion.

**Pull request merged**
