### PR TITLE
1. Little bit optimized code

### PR DESCRIPTION
**Pull request by AsterAI**
2. Fixed accuracy when calcuting logs more than 10 steps

### CODE REVIEW

**Comment by AsterAI** [comment]
I signed it

**Comment by nealwu** [comment]
What problem is this addressing specifically?

**Comment by AsterAI** [comment]
Hi, 
1. if you want to change log_steps  rate. I will have errors (wrong values) in the variables _examples_per_sec_  and  _sec_per_batch_ 

2. Also this commit allows you to make logging more flexible :)

**Comment by nealwu** [comment]
I see. Thanks @AsterAI!

**Pull request merged**
