### PR TITLE
Use batch_norm in contrib/layers/python/layers/layers.py in Resnet model

### PR DESCRIPTION
**Pull request by Kongsea**
Fix a TODO using batch_norm in contrib/layers/python/layers/layers.py in Resnet model.

### CODE REVIEW

**Comment by Kongsea** [comment]
Yes, it's a typo. Now I have fixed it. I'm sorry for this mistake.

**Comment by panyx0718** [comment]
How's the accuracy of cifar10 and ciar100 after the change?

**Comment by Kongsea** [comment]
I have not tested on cifar10 or cifar100. I just tested it in our own project using our dataset and the accuracy is almost the same as before.

**Comment by karmel** [comment]
@panyx0718 Is this PR still relevant? Can you merge or close?

**Comment by tfboyd** [comment]
Closing very old PRs.  I do not like seeing work lost.  I and others are working to accept any changes to /official; but changes to other directories require the original owner to take action.  I am sorry this change died/stalled.

I am copy and pasting this message in each PR I a closing (yes kind of like an automated response); and I want to say I feel this way about each PR and wish they had ended with a merge or some other more positive finality.  

Thank you for your contribution and time.

**Pull request closed without merging**
