### PR TITLE
Transfer tensorflow's internal models to tensorflow/models repository

### PR DESCRIPTION
**Pull request by keonkim**
This is the pull request fixing problem #361.

If I am correct, [tensorflow.models](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/models) is being deprecated.
But some models are still kept inside this directory because of tensorflow tutorials. 
I think it would be more straight forward and relevant to keep all the model implementations in tensorflow/models repository.

I was able to extract all commit history of each files.

### CODE REVIEW

**Comment by keonkim** [comment]
I think it is going to be a huge spam if I just add everyone here. Should I add everyone here?

**Comment by martinwicke** [comment]
No, this is fine. We know it's a cherry-pick.

**Comment by drpngx** [comment]
Is this still valid? If so, can you sign the CLA?

**Comment by keonkim** [comment]
@drpngx I signed CLA. But the bot is concerned that I am not the one who actually wrote the code.

**Comment by martinwicke** [comment]
@drpngx This is in effect a merge (cross-repo, but still a merge), so the CLA is fine. The problem is that we're still not done with our tutorials/example reorg, so it will have to wait some more.

**Comment by drpngx** [comment]
Got it, thanks! Closing. Please reopen once we're done with the reorg, or ping if we take too long.

**Pull request closed without merging**
