### PR TITLE
Replace old tf.nn modules with 1.0-compatible versions

### PR DESCRIPTION
**Pull request by nealwu**
Fixes https://github.com/tensorflow/models/issues/1187 and https://github.com/tensorflow/models/issues/1181

### CODE REVIEW

**Comment by tifoit** [comment]
Tensorflow 0.9 to 1.0.1 is a big jump. A lot changed.
Details: https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

In tf 1.0.0, the API has been changed such as:

tf.nn.seq2seq.sequence_loss_by_example
to
tf.contrib.legacy_seq2seq.sequence_loss_by_example

tf.nn.rnn_cell.
to
tf.contrib.rnn.

tf.nn.rnn_cell.MultiRNNCell(
to
tf.contrib.rnn.MultiRNNCell(

...

**Comment by nealwu** [comment]
@tifoit This is an old pull request. Is there some code you found in the [current version of the repository](https://github.com/tensorflow/models) that is not yet upgraded to TF 1.0+? If so, let us know.

**Comment by iamharshit** [comment]
@nealwu this issue is still present in tf 1.2. Please check it once again

**Comment by nealwu** [comment]
@iamharshit What issue is present?

**Comment by iamharshit** [comment]
If i do:
```
logits, state =  tf.contrib.legacy_seq2seq.embedding_rnn_seq2seq(encoder_inputs,decoder_inputs,cell, num_encoder_symbols,num_decoder_symbols,embedding_size,)

loss = tf.contrib.seq2seq.sequence_loss(logits,targets,weights,)

```
then it gives erorr
```
AttributeError: 'list' object has no attribute 'get_shape'
```
referering to the variable logits as list

**Comment by nealwu** [comment]
Where is the code you are referring to? Is it in this models repository? If it is your own code, you should [ask on StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

**Pull request merged**
