### PR TITLE
Edits to pass mnist_eager_test.py

### PR DESCRIPTION
**Pull request by hsm207**
These edits will still fail mnist_test.py

### CODE REVIEW

**Comment by asimshankar** [comment]
Could you elaborate on the problem? Note that the master branch of the models repository may depend on features in the master branch of the TensorFlow repository. So, if you're looking for compatibility with a particular release of TensorFlow, then you should use the corresponding branch in the models repository.

**Comment by hsm207** [comment]
@asimshankar The problem and its source is discussed in #3491.

I stumbled upon this error while reading [this ](https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html)blog post. It says I we can convert the model to graphs by running the same code without eager execution enabled and pointed readers to [this ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/eager/python/examples/mnist)repository which pointed to mnist_eager.py. But mnist_eager,py won't even execute because due to #3491.

**Comment by asimshankar** [comment]
@hsm207 - I've added a comment to #3491 as well. Which version of TensorFlow are you using? The blog post refers to the nightly version of TensorFlow (which will be compatible with this). But if you're using TensorFlow 1.5 or something, then you want to use the r1.5 branch of this repository.

Let us know if that works or not. Thanks.

**Comment by hsm207** [comment]
@asimshankar I am using TensorFlow 1.5. The r1.5 branch does not have mnist_eager.py.

You are right, running mnist_eager_test.py using the nightly version (1.7.0-dev20180302) works.

Thank you for your clarification.

Should I delete this pull request?

**Comment by asimshankar** [comment]
Yes, let's delete it. Thanks.

**Comment by Katze123456** [comment]
pls help

**Pull request closed without merging**
