### PR TITLE
Fix two issues with tensorflow_models/slim downloading imagenet.

### PR DESCRIPTION
**Pull request by joel-shor**
@nealwu @sguada 
1) Fix word dir
2) Fix download url

Corresponds to cl/176965289.

### CODE REVIEW

**Comment by joel-shor** [comment]
@shlens as well

**Comment by scotthuang1989** [comment]
@joel-shor  I apply your patch. still get this error: 

> ./download_and_convert_imagenet.sh: line 67: ./download_and_convert_imagenet.sh.runfiles/__main__/datasets/download_imagenet.sh: No such file or directory

I guess it is related to bazel. but I don't find any instruction in the readme.md to work around this. how do you do it?

**Comment by joel-shor** [comment]
With the code in the PR, I *don't* get that error. '__main__' renders fine.

Is there someone who owns this code and can get it to work? If not, it should probably be deleted.

**Comment by joel-shor** [comment]
I don't get that error. Also, to be sure, the word `main` in your code is actually surrounded by two underscores, correct?

What was the command you used?

**Comment by scotthuang1989** [comment]
@joel-shor   I just change my working directory to  

> research/slim/datasets

 and execute  

> download_and_convert_imagenet.sh
I don't do any other actions. I miss something?

**Comment by joel-shor** [comment]
The instructions are wrong. It needs to be built with bazel. I'll make the
change shortly.

**Pull request merged**
