### PR TITLE
Align model slim/resnet to slim/inception

### PR DESCRIPTION
**Pull request by stef716**
Align model slim/resnet to slim/inception (set spatial_squeeze and default_image_size).
Also add a sample script for training resnet_v1_50 on flower set.

This solves #690

### CODE REVIEW

**Comment by ahundt** [comment]
I tested this and it works for me! The new script is also a very helpful demonstration, much better than what is in the README.md.

However, regarding the the various default image size parameters like `resnet_v2_200.default_image_size = 224`: should those really be a scalar? Could this break fcn mode where dense predictions are made and images can be rectangular?

**Comment by stef716** [comment]
@ahundt I added these defaults to all resnet models because the current interfaces require it.
I think the squared image extracts are typical for supporting the mixed datasets of portrait and landscape images. In fixed camera environments you definitely want non-squared aspect ratios depending on your scenario. Train, Eval scripts and models could easily be extended. But would be a different issue.

**Comment by ahundt** [comment]
seems sensible

**Comment by nealwu** [comment]
Thanks!

**Pull request merged**
