### PR TITLE
update sequence loss to contrib from legacy

### PR DESCRIPTION
**Pull request by EvanKepner**
Hi - this PR updates the reference from the legacy_seq2seq sequence loss by example to the seq2seq sequence loss in the RNN Penn Treebank tutorial.

### CODE REVIEW

**Comment by nealwu** [comment]
@ebrevdo could you review this?

**Comment by ebrevdo** [comment]
What version of tf are we targeting with the ptb example?  Not all users
have tf.contrib.seq2seq.

**Comment by nealwu** [comment]
We want the models repo to be compatible with TF 1.0+. When was `tf.contrib.seq2seq` added?

**Comment by ebrevdo** [comment]
After version 1.0.

**Comment by nealwu** [comment]
Then using `tf.contrib.seq2seq` should be fine here (as long as the code works). Can you let us know whether it looks good to you?

**Comment by EvanKepner** [comment]
Thanks for considering this PR! Here are the results I get running with `contrib.seq2seq.sequence_loss` versus `contrib.legacy_seq2seq.sequence_loss_by_example` on a Tesla K80:

### Original values (contrib.legacy_seq2seq) from doc-string
| config | epochs | train | valid  | test |
|---|---|---|---|---|
| small  | 13 | 37.99 | 121.39 | 115.91
| medium | 39 | 48.45 |  86.16 |  82.07
| large  | 55  | 37.87 |  82.62 |  78.29

### Values with updated cost function (contrib.seq2seq)
| config | epochs | train | valid  | test |
|---|---|---|---|---|
| small  | 13 | 41.098 | 119.169 | 113.733
| medium | 39 | 45.795 |  87.942 |  84.511
| large  | 55  | 37.986 |  82.619 |  78.105

**Comment by EvanKepner** [comment]
@nealwu @ebrevdo any thoughts on additional code changes? Thanks again for reviewing the PR

**Comment by nealwu** [comment]
Hi @lukaszkaiser could you do a quick review of this? Looks like Eugene is out on vacation.

**Comment by EvanKepner** [comment]
Awesome - thank you @lukaszkaiser @nealwu!

**Comment by marlazinger200** [comment]
1

**Pull request merged**
