### PR TITLE
mask evaluation from record (issues: 9957, 9980)

### PR DESCRIPTION
**Pull request by anshkumar**
This PR allows maskrcnn evaluation to be done directly from record file. This will be useful in deepmac_maskrcnn.

### CODE REVIEW

**Review by arashwan — DISMISSED** [review]

**Comment by saberkun** [comment]
np.generic inclue np.btypes. The code does not work. I am changing to np.array only for the internal process now.

**Comment by saberkun** [comment]
@arashwan there are multiple failures according to the internal tests. Please check.

**Comment by anshkumar** [comment]
> @arashwan there are multiple failures according to the internal tests. Please check.

What kind of failures ?

**Comment by anshkumar** [comment]
@saberkun I've added mask resizing in `maskrcnn_input.py` which should fix errors. I'm using `np.generic` just to check whether `groundtruths['masks'][i][j, k]` is an instance of numpy or not. I've tested using coco validation record. Please let me know if it's working fine.

**Comment by arashwan** [comment]
This PR causes OOM due to saving the masks into the memory. We have supported eval from record by generating the annotation.json if annotation file isn't provided. https://github.com/tensorflow/models/commit/e0ad9ff2daf3c7771161dcd6f8b76ccf5d4181c4

**Pull request closed without merging**
