### PR TITLE
Adding a google cloud container builder spec to build cpu and gpu based images

### PR DESCRIPTION
**Pull request by vishh**
To setup continuous builds of container images that will includes all the models in this repo via [google cloud container builder](https://cloud.google.com/container-builder/), this PR introduces a container builder configuration file that explicitly specified the images that will be built for every commit to this branch and more importantly the need for a larger size VM to run these builds in the background.

To submit builds manually to container builder run the following command:
```shell
$ cd official 
$ gcloud container builds submit --config cloudbuild.yaml . --project <your-gcp-project> --substitutions=COMMIT_SHA=$(git rev-parse HEAD)
```

Builds will be automated via container builder and you can list the images available periodically as follows:
```shell
$ gcloud container images list-tags gcr.io/tensorflow/models
$ gcloud container images list-tags gcr.io/tensorflow/models-gpu
```

### CODE REVIEW

**Comment by vishh** [comment]
@karmel This is needed to run gpu builds automatically.

**Comment by robieta** [comment]
Can you put a blurb at the top about what this is?

**Comment by karmel** [comment]
This is great, @vishh , thanks. It is hard for me to review the actual config, but other than the request for docs from @robieta above, LGTM. Is there a link/demo/doc we can reference as well that shows this in action?

**Comment by vishh** [comment]
@karmel @robieta I have updated the PR description. PTAL.

**Comment by tfboyd** [comment]
Cleaning up all PRs targeting official.  This is 6+ months old and never merged.  We can bring this back and if so we may want to add to a README.md as a user would find this .yaml file at root with no description and wonder what it is.  

I would love to have a continuous builder for containers for different GPU configs via docker without wasting my GPU test servers cycles.  Have not had time to dig into the tool.

**Pull request closed without merging**
