### PR TITLE
Simple README change

### PR DESCRIPTION
**Pull request by arvind2505**
Maintaining only for Tensorflow version 0.10

### CODE REVIEW

**Comment by nealwu** [comment]
Hi @arvind2505 is it not possible for you to maintain for TensorFlow 1.0+? All the models in this repository have been converted to the TF 1.0 APIs in a few previous pull requests.

**Comment by arvind2505** [comment]
Hi @nealwu: Yes, I will try to get back to it ASAP. Meanwhile, I just want to make it clear that I can answer only questions for 0.10 for now as was discussed in another thread.

**Comment by nealwu** [comment]
I see, but unfortunately the model code is already incompatible with TF 0.10 since the upgrade PR. Is there anything in particular that is blocking you from maintaining it as a TF 1.0+ model?

**Comment by arvind2505** [comment]
Okay, I just went through all the changes. I can maintain it. Thanks for the help!

**Comment by nealwu** [comment]
Ok sounds good! Sure thing.

**Pull request closed without merging**
