### PR TITLE
 fixes Perspective Transformer IOU evaluation

### PR DESCRIPTION
**Pull request by mees**
fixes IOU computation for issue #2239

### CODE REVIEW

**Comment by mees** [comment]
Here is the fix @arkanath @xcyan

**Comment by xcyan** [comment]
Looks good to me.

**Comment by xxxzhi** [comment]
what's about label 255 at ground truth.

**Comment by xcyan** [comment]
@xxxzhi Can you be more specific?

**Comment by xxxzhi** [comment]
@xcyan In segmentation groud truth label, there are some label who's value is 255 which means fuzzy tag.  This method tf.contrib.metrics.streaming_mean_iou will fail to call.

https://github.com/tensorflow/tensorflow/commit/6ac3efd42902d48d45d59128926110e6d5121a08

**Comment by xcyan** [comment]
@xxxzhi Are you talking about a bug specific to this PR? or a bug specific to tensorflow/models/ptn? I don't think we have segmentation label who's value is 255.

**Comment by xxxzhi** [comment]
@xcyan I'm taling about https://github.com/tensorflow/tensorflow/commit/6ac3efd42902d48d45d59128926110e6d5121a08 . I use a label who's value is 255, then I fail to call that function. This PR is nice.

**Comment by xxxzhi** [comment]
@xcyan I often use label 255 for ignore label in segmentation.

**Comment by mees** [comment]
@xxxzhi I don't really understand the discussion. @xcyan maps the prediction to 3(free) and 1(occupied) and the gt to 2(free) and 1(occupied) and thus gets the intersection for 1. My patch just makes so that it starts with 0 instead of 1, because that was causing problems. I don't think that with this code you will get a value of 255 as a label, but maybe I didn't understand your concern correctly.

**Comment by xcyan** [comment]
Anyways, this PR looks good. Please file another bug/feature request for discussions not related to this PR.

**Comment by xcyan** [comment]
@hellojas Please review this PR at your convenience. Thanks!

**Comment by xcyan** [comment]
@hellojas Please review & merge this PR if possible. Thank you!

Best,
Xinchen

**Pull request merged**
