### PR TITLE
fix ImageNet scripts and description

### PR DESCRIPTION
**Pull request by freedomtan**
newly added scripts for download and convert ImageNet dataset don't work. Mostly because of  different path.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
Nice, I was just about to do this.

**Comment by thesuperzapper** [comment]
Hey guys LGTM, the download script literally doesn't work in master right now. 

But neither will this PR until one small thing is added, [slim/datasets/download_imagenet.sh#105](https://github.com/freedomtan/models/blob/78c50bdb41c6b3a21e9e9599f2dd47aa1b0533e9/slim/datasets/download_imagenet.sh#L105) needs to be changed from `done < "${SYNSETS_FILE}"` to `done < "${CURRENT_DIR}/${SYNSETS_FILE}"` 

I just tested using the script with this PR and the above change, and it worked like a charm.

**Comment by thesuperzapper** [comment]
@sguada @freedomtan

**Comment by skoppula** [comment]
Yeah, can confirm, the ImageNet scripts don't work on master. Fixed the BUILD script manually on my end, until a bit of searching yielded the PR. Virtually the same changes.

**Comment by freedomtan** [comment]
I rebased the patch and added what @thesuperzapper suggested

**Pull request closed without merging**
