### PR TITLE
Create slim_walkthrough_multi_gpu.ipynb

### PR DESCRIPTION
**Pull request by woodthom2**
I've added an adaptation of the flowers retraining demo but for multiple GPUs, so you can train all of the models in Slim now making full use of a GPU array.

### CODE REVIEW

**Comment by woodthom2** [comment]
I signed it!

**Comment by nealwu** [comment]
Hi @woodthom2, are you still interested in merging this in? I noticed there have been a number of changes to the original slim_walkthrough.ipynb since you created this pull request (mainly API changes for TensorFlow 1.0). Those would certainly need to be updated before merging this in.

**Comment by woodthom2** [comment]
Hi @nealwu, I think now that we don't need to merge it as there are other multi-GPU tutorials such as https://www.tensorflow.org/tutorials/using_gpu#using_multiple_gpus so I think it doesn't add anything new. Thank you

**Comment by nealwu** [comment]
OK, thanks!

**Pull request closed without merging**
