### PR TITLE
Adding new checkpoints for Resnets

### PR DESCRIPTION
**Pull request by karmel**

### CODE REVIEW

**Comment by karmel** [comment]
The files here seem to be giving the wrong accuracy; closing this while I sort out what happened.

**Comment by karmel** [comment]
Reopening, as the checkpoints seem to work with master + tf-nightly.

**Comment by karmel** [comment]
@robieta , in the interest of minimizing the time during which we are wrong, how do you feel about merging this, and then updating with the checkpoints/savedmodels from #3687 when they are ready and that is in? You can ditch the Frozen Graphs at that point.

cc @qlzh727 - it would be nice if the benchmarks stuck their checkpoints and savedmodels somewhere were we could just link to a directory, and tell people to take the most recent ones, rather than manually updating.

**Comment by robieta** [comment]
Agreed. That seems like the most sensible approach.

**Pull request merged**
