### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by reedwm**
Also test to see if the tests pass.

### CODE REVIEW

**Comment by saberkun** [comment]
Can we get this kind of changes internally? Otherwise, PR needs to go through gerrit

**Comment by reedwm** [comment]
I made a PR because I want to test if the tests pass. I want to see if #7474 fails the tests due to a bug in the PR or due to the fact the tests are currently failing at the master branch.

This doesn't have to be merged.

**Comment by saberkun** [comment]
I did the same thing. The tests are passing...

**Comment by jaeyounkim** [comment]
I am closing this PR because we made many changes already.

**Pull request closed without merging**
