### PR TITLE
Update autoencoders

### PR DESCRIPTION
**Pull request by alanyee**
-Fix styling of print statements
-Added Python 2 compatibility
-Fixed code according to PEP 8

### CODE REVIEW

**Comment by alanyee** [comment]
@snurkabill How does this look to you?

**Comment by snurkabill** [comment]
Great small commits, I like it. Thanks!

**Comment by alanyee** [comment]
@snurkabill are you able to merge it?

**Comment by snurkabill** [comment]
@alanyee  actually I can't, don't have such rights here. What about @martinwicke for example?

**Comment by snurkabill** [comment]
Thank you @martinwicke

**Pull request merged**
