### PR TITLE
Resnet transfer learning

### PR DESCRIPTION
**Pull request by zacwellmer**
This is an extension of [this PR](https://github.com/tensorflow/models/pull/5036). I opened a new pull request b/c my previous commits were done without a configured gitconfig

### CODE REVIEW

**Comment by robieta** [comment]
It looks like you're failing lint and unit tests. If you run `official/utils/testing/scripts/presubmit.sh` it should tell you exactly what's broken.

**Comment by zacwellmer** [comment]
@robieta So I fixed I fixed the unit test and lint errors related to the scripts I updated. However, since I made these changes from a remote instance it looks like it somehow resurfaced the previous issues with the CLA. Should I redo these commits again under a new PR?

**Comment by robieta** [comment]
I would say just drop the lint commit, re-apply the changes on the properly configured machine, and then force push.

**Comment by robieta** [comment]
Actually, it looks like the issue is with the first commit. Squashing and force pushing on the good machine should work. (Make sure to dump a patch file first)

**Comment by zacwellmer** [comment]
@robieta Should I be concerned about failing the Python2 and Python3 checks? If so do you have any scripts you recommend using that will flag what's generating the errors? The errors from ```official/utils/testing/scripts/presubmit.sh``` related to the scripts I updated have been fixed.

**Comment by robieta** [comment]
It looks like the presubmit script isn't running the unit tests by default. (I will be the first to admit we haven't done a good job documenting for external contributors)
`official/utils/testing/scripts/presubmit.sh py3_test` should work.

Looking over the failures, they all seem to be of the form:
```
======================================================================
ERROR: test_cifar10_model_fn_eval_mode_v1 (__main__.BaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./resnet/cifar10_test.py", line 123, in test_cifar10_model_fn_eval_mode_v1
    dtype=tf.float32)
  File "./resnet/cifar10_test.py", line 91, in cifar10_model_fn_helper
    'loss_scale': 128 if dtype == tf.float16 else 1,
  File "/tmpfs/src/github/tensorflow_models/official/resnet/cifar10_main.py", line 225, in cifar10_model_fn
    fine_tune=params['fine_tune']
KeyError: 'fine_tune'
```

Or you can just run every file in the resnet/ folder that ends with `_test.py`

**Comment by robieta** [comment]
Perfect.

**Comment by robieta** [comment]
Everything looks good. Thanks for your submission; this is a lovely PR.

**Comment by zacwellmer** [comment]
Thanks, might be nice for some tests to be added for fine_tuning. This is pretty fragile to naming changes of the final layer. For example if it changes from having "dense" in the variable name this will break

**Pull request merged**
