### PR TITLE
Fix bug of class DenseEinsum

### PR DESCRIPTION
**Pull request by ZhuBaohe**
This pr fixs bug of class DenseEinsum.

### CODE REVIEW

**Comment by saberkun** [comment]
Thanks!
Do you know how to trigger the bug and what's the effect?

**Comment by ZhuBaohe** [comment]
> Thanks!
> Do you know how to trigger the bug and what's the effect?

@saberkun 

This is a test code.
 
```
import numpy as np
from official.nlp.modeling.layers import dense_einsum

test_layer = dense_einsum.DenseEinsum(output_shape=(64,), num_summed_dimensions=2)
input_tensor = tf.constant(np.random.random_sample((10, 20, 40, 80)))
print(test_layer.compute_output_shape(input_tensor.shape))
```
Before fixed, it shows error
`AttributeError: 'DenseEinsum' object has no attribute '_units'`

After fixed, it shows the right result
`(10, 20, 64)`

**Comment by saberkun** [comment]
@ZhuBaohe Thanks!
Discussing with Keras team. It seems that tf.keras does not need to implement compute_output_shape.
Will get back with conclusion.

**Comment by saberkun** [comment]
Confirmed with keras team. We don't need compute_output_shape.
compute_output_shape is only used when layer.dynamic = True

**Pull request closed without merging**
