### PR TITLE
custom_regression made compitable with TF2.x

### PR DESCRIPTION
**Pull request by ayushmankumar7**
Issue :  #8231

Since the aim of the Repo is to convert most of their models compatible with TF 2.x so, i made this example compatible with TF 2.x.

### CODE REVIEW

**Comment by MarkDaoust** [comment]
Hi @ayushmankumar7, thanks for taking the time to send a PR.

Really, at this point I should just delete this directory.

If you do want to fix this, wouldn't it be simpler to `import tensorflow.compat.v1 as tf`?

**Comment by ayushmankumar7** [comment]
Oh.. Yes.. Lemme do it that way. Thanks for the tip

**Comment by MarkDaoust** [comment]
I deleted it. I was hoping to link the deletion (#8234) on here before you did any more work.

I hope I didn't waste too much of your time. 

Thanks again for taking the time to help out.

**Comment by ayushmankumar7** [comment]
No probelm @MarkDaoust . It's alright. Could you suggest me some issues to work on?

**Pull request closed without merging**
