### PR TITLE
Add pr_curve for object detection api for issue #3081

### PR DESCRIPTION
**Pull request by foreverYoungGitHub**
Add pr_curve for object detection api for issue #3081.

Change few functions mentioned in issue #3081 without add new ones. Tested with the newest tensorboard.

### CODE REVIEW

**Comment by zeynali** [comment]
@Fahimkh , Hi Dear , did you solve your problem ? i faced with this error.

**Comment by foreverYoungGitHub** [comment]
Let me check it later. I may update it here if I figure out any problem.

**Comment by Fahimkh** [comment]
@zeynali I did not.. But now I am plotting PR curve after compute_precision() function...

**Comment by zeynali** [comment]
@zeynali  HOW? please help me

**Comment by Fahimkh** [comment]
@zeynali There is a file in 'util' folder with name 'object_detection_evaluation.py'. In this file there is class 
class ObjectDetectionEvaluation(object)

then go to function with this name 'def evaluate(self):'

In this function you are getting precision and recall by using following function 

precision, recall = metrics.compute_precision_recall(
          scores, tp_fp_labels, self.num_gt_instances_per_class[class_index])

Simply plot this precision and recall values..  If you get any problem then let me know..

**Comment by zeynali** [comment]
@Fahimkh ,Hi, i have added your command such this , is it right ? and i add return precision and recall : 
[...............................]
       # PR curve
        display_name = (
            'PR_curve@{}'.format(category_index[idx + self._label_id_offset]['name']))
        pr_value[display_name] = {'precisions': precisions_per_class[idx], 'recalls': recalls_per_class[idx]}

        # Optionally add CorLoc metrics.classes
        if self._evaluate_corlocs:
          display_name = (
              self._metric_prefix + 'PerformanceByCategory/CorLoc@{}IOU/{}'
              .format(self._matching_iou_threshold,
                      category_index[idx + self._label_id_offset]['name']))
          pascal_metrics[display_name] = per_class_corloc[idx]

     	precision, recall = metrics.compute_precision_recall(
		scores, tp_fp_labels, self.num_gt_instances_per_class[class_index])  

    return pascal_metrics , pr_value , precision , recall

##################################
is this ok ? if so , now if i run eval.py then where are both precision and recall of values printed ? i am a new in tensorflow , Please give me more guidance. thanks.

**Comment by Fahimkh** [comment]
@zeynali 
I am not returning it but plotting these values... using python library mathplotlib... by following way...

precision, recall = metrics.compute_precision_recall(
	scores, tp_fp_labels, self.num_gt_instances_per_class[class_index])
plt.figure()
plt.step(recall, precision, where='post' )
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.xlim((0, 1))
plt.ylim((0, 1))
plt.show()
plt.close()

and add this line at top of this file

import matplotlib.pyplot as plt

**Comment by zeynali** [comment]
@Fahimkh , I just only add these to this file? Removed the rest of what you said?

**Comment by Fahimkh** [comment]
@zeynali  NO.. add these extra lines in your file.. Can you please tell me in little bit detail what are you trying to achieve.. So I can guide you.

**Comment by zeynali** [comment]
@Fahimkh , Hi , in fact i'v trained ssd_mobile_coco on my own dataset using Object Detection Api , i have some question about this ?
1) i want to add some Api codes  to show me mAP ,Recall , Precision on Tensorboard.
2) i want to run both train/eval.py at same time to view mAP,.... like TotalLoss , ...
but when i run train.py in one Terminal window , this allocate whole of GPU Memory for training , when i run eval.py in the other Terminal window , i get OOM error.

**Comment by bhack** [comment]
Actually in the Object detection API there is also segmentation. Do you suppose to cover something like F in https://github.com/fperazzi/davis/blob/master/python/lib/davis/measures/f_boundary.py

**Comment by Fahimkh** [comment]
@zeynali
I did not plot it in tensorboard..

**Comment by Fahimkh** [comment]
@zeynali
I plotted it using matplotlib

**Comment by zeynali** [comment]
@Fahimkh , please give me your codes and explain about how is working and what should i do ?

**Comment by zeynali** [comment]
@Fahimkh , Hi , when i've trained the one models of in model zoo , for plot recall-precision curve what do i do ? you said this command:

import matplotlib.pyplot as plt
precision, recall = metrics.compute_precision_recall(
scores, tp_fp_labels, self.num_gt_instances_per_class[class_index])
plt.figure()
plt.step(recall, precision, where='post' )
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.xlim((0, 1))
plt.ylim((0, 1))
plt.show()
plt.close()

my question is where these commands i added ?

**Comment by austinmw** [comment]
@zeynali search for the already existing line `precision, recall = metrics.compute_precision_recall(
scores, tp_fp_labels, self.num_gt_instances_per_class[class_index])` and just add the `plt` lines right after that, then at the import line to the very top

**Comment by MjdMahasneh** [comment]
@austinmw @Fahimkh I understand what you guys are trying to do, the only thing am not sure of is how to get these plots? is it by running eval.py? (i.e. python eval.py --logtostderr --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config --checkpoint_dir=training/ --eval_dir=eval)

**Comment by anacej** [comment]
Same question here, running the eval.py script, nothing is plotted.

**Comment by anacej** [comment]
are there any updates for plotting PR curve in new API?

**Comment by Hafplo** [comment]
Added these changes manually to the source code and it works!
Not sure if the curve is valid since it looks very smooth.
Would be very helpful to review this pull request and add it as official feature.

**Comment by Hafplo** [comment]
> @Hafplo Hi, can share where you make the changes and is your curve on tensorboard?
> thanks

We manually inserted this commit (just go to "commits" or "files changes" links). We had to debug some issues (not familiar with the details).
Now our events files in evaluation include the pr_curves and we are able to see them in our Tensorboard - there is a tab called "PR curves" in addition to the regulars ("Scalars", "Images", "Graph", etc.)

**Comment by krustiv** [comment]
@Hafplo  thank you for your reply. I've run the commited file for training but tensorboard still do not show the expected "PR Curves" tab. 
Training still can go on. Will PR curves show for training?

**Comment by austinmw** [comment]
@foreverYoungGitHub Any idea how to update this for v1.12.0?

**Comment by Hafplo** [comment]
@austinmw Unfortunately I do not have exact details and cannot share it.
From what I see, we just copied the changes in this PR to our files. I do remember we had some bugs due to wrong indentation. This is just silly human error because we copied manually.

**Comment by austinmw** [comment]
@Hafplo thanks for your reply. What version of TF are you using? This PR shouldn't work with current versions without more significant changes.

**Comment by Rakiba291** [comment]
can anyone share the correct files of  eval_util.py and object_detection_evaluation.py  files with tensorflow version 1.12 ? Im new to tensorflow, so if anyone can explain step by step process to see the PR curves on tensorboard, will be very helpful. 
Thanks in advance!

**Comment by Hafplo** [comment]
@austinmw we use 1.12

**Pull request closed without merging**
