### PR TITLE
Make textsum compatible with Python 3

### PR DESCRIPTION
**Pull request by nealwu**

### CODE REVIEW

**Comment by nealwu** [comment]
@studynon, can you confirm that this works for you?

**Comment by nealwu** [comment]
@jhseu is this the correct way to import Queue from six?

**Comment by studynon** [comment]
@nealwu , The way of your using six.moves.queue will make an error. If you want to use six.moves, the code should be 
"from six.moves import queue as Queue".
This works for me.

**Comment by nealwu** [comment]
Thanks @studynon. Fixed.

**Pull request merged**
