### PR TITLE
fix issue 'could not satisfy explicit device'

### PR DESCRIPTION
**Pull request by zengsn**
Some local operations require CPU instead of GPU.
And I found a lot of users raised the same issue in tensorflow/tensorflow, like 
https://github.com/tensorflow/tensorflow/issues/3475  
https://github.com/tensorflow/tensorflow/issues/14085  

And in tensorflow/models, #1823 

I think adding these two lines should help to avoid confusing.

### CODE REVIEW

**Comment by zengsn** [comment]
I signed it!

**Comment by zengsn** [comment]
@sguada Call for review. :)

**Comment by zengsn** [comment]
How about you take a look for me, @robieta ?

**Comment by robieta** [comment]
This all looks reasonable. I'll follow up.

**Comment by zengsn** [comment]
@robieta I hope that you haven't forgotten this thread. :)

**Comment by robieta** [comment]
I have not. Thanks for being so patient.

@karmel Are you able to approve this?

**Comment by zengsn** [comment]
@robieta I am glad to get your response. Thanks.

**Pull request merged**
