### PR TITLE
Add option to configure max GPU memory fraction for training and evaluation in object_detection

### PR DESCRIPTION
**Pull request by ArjanSchouten**
**Subfolder**: object_detection
**Use Case**:
I want to follow the accuracy over time during training. I run train.py and eval.py at the same time. train.py is directly allocating all GPU VRAM so eval.py can't restore the graph anymore and results in OOM (since I use one GPU).

**Changed method definition:**
An additional parameter is added in eval_util.py (method repeated_checkpoint_run and run_checkpoint_once). If this is problematic then I would suggest leaving the config option for eval and only add the option to train.proto.

### CODE REVIEW

**Comment by ArjanSchouten** [comment]
I signed it!

**Comment by ArjanSchouten** [comment]
I signed it!

**Comment by Briannairish** [comment]
I signed it!

**Comment by ArjanSchouten** [comment]
Sorry everyone for this messed up PR. Tried to fix wrong email address for cla check.

**Pull request closed without merging**
