### PR TITLE
Update running_pets.md

### PR DESCRIPTION
**Pull request by Vyas9296**
Line 219 runtime version updated to 1.9, current version of 1.8 will trigger 'TypeError: non_max_suppression() got an unexpected keyword argument 'score_threshold'' on the Google Cloud since 1.8 and older does not support this keyword argument.

### CODE REVIEW

**Comment by Vyas9296** [comment]
I signed it!

**Comment by Vyas9296** [comment]
Updated doc line 211

**Comment by arinto** [comment]
should we update the [object_detection/samples/cloud/cloud.yaml](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/cloud/cloud.yml#L2) as well?

**Comment by Vyas9296** [comment]
Thanks @arinto, have updated the runtime version as well. Also re-emphasised in the doc that Tensorboard and Tensorflow need matching minor versions (1.x).

**Comment by arinto** [comment]
I meant runtime file in `object_detection/samples/cloud/cloud.yaml` file. Is it working without updating the runtime version in that file? 
Or the runtime version from that config file is overwritten by CLI flag from README.

**Comment by Vyas9296** [comment]
Hi @arinto, thanks for pointing that out. I think it is overwritten, because I ran training successfully with both 1.8 and 1.9 in the cloud.yml file. But we should update to 1.9 for consistency. Do I need to create a new pull request for that? I don't think I can add it to this one

**Pull request merged**
