### PR TITLE
add a Ubuntu 14.04 x86 build script

### PR DESCRIPTION
**Pull request by JoshData**
Hello all,

It was tricky figuring out exactly how to build everything. I packaged up all of the steps I took on a fresh Ubuntu 14.04 x64 machine and thought it would be useful for others if included here.

Interested?

Thanks for your great work on this.

### CODE REVIEW

**Comment by JoshData** [comment]
I signed it!

**Comment by QuanxinZhao** [comment]
Hi Joshua,

I installed Ubuntu (14.04.4 LTS Trusty Tahr 64-bit PC AMD64 desktop image) in Vmware. 
There are some error messages below when using the code 'syntaxnet/build/ubuntu-14.04_x64.sh'.
Can you please give more version information about the software and hardware you have tested successfully?
Thank you.


ERROR: /home/a2/Desktop/models/syntaxnet/bazel_root/3e7bfaa971aeb85c5745b45ebbc65906/external/tf/tensorflow/core/kernels/BUILD:934:1: C++ compilation of rule '@tf//tensorflow/core/kernels:argmax_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 81 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
INFO: Elapsed time: 968.907s, Critical Path: 879.60s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                       NO STATUS
//syntaxnet:graph_builder_test                                              NO STATUS
//syntaxnet:lexicon_builder_test                                            NO STATUS
//syntaxnet:parser_features_test                                           NO STATUS
//syntaxnet:parser_trainer_test                                              NO STATUS
//syntaxnet:reader_ops_test                                                  NO STATUS
//syntaxnet:sentence_features_test                                      NO STATUS
//syntaxnet:shared_store_test                                               NO STATUS
//syntaxnet:tagger_transitions_test                                       NO STATUS
//syntaxnet:text_formats_test                                                NO STATUS
//util/utf8:unicodetext_unittest                                               NO STATUS

Executed 0 out of 12 tests: 12 were skipped.

**Comment by JoshData** [comment]
> gcc: internal compiler error: Killed (program cc1plus)

That sort of error is often an out of memory thing. I wasn't able to run it within Vagrant --- I spun up a high-memory AWS instance. As I wrote in the PR:

> The build process requires about 22 GB free memory and 2 GB free disk space.

So make sure you have a machine with at least that! I think I used a 64 GB machine. Probably less memory is required to run it after it builds (but I didn't try it).

**Comment by QuanxinZhao** [comment]
Hi Joshua,

Thank you very much.
I have solved the out of memory problem.

**Comment by MinionAttack** [comment]
I think you don't need a 64GB machine to build it. I could build it on a 16GB desktop machine. I only needed update the gcc ubuntu version. By default, ubuntu 14.04 comes with **gcc 4.8.2** so If you update it to **4.9.x** or newer this solves the problem of _gcc: internal compiler error: Killed (program cc1plus)_ I have the **gcc (Ubuntu 6.1.1-3ubuntu11~14.04.1) 6.1.1 20160511** .

This worked for me, hope it helps someone.

**Comment by thinkingin** [comment]
I ran in a 4gb ubuntu faced the same issue and later increased the virtual
memory and it worked.

**Comment by renjinghai** [comment]
Thanks Josh
I also has similar problem as QuanxinZhao. It is resolved and the root cause is the memory.
I'm using virtualbox and Ubuntu image from http://www.osboxes.org/ubuntu/#ubuntu-14_04-vbox.
Set 4 cpus and **12GB** memory to the VM.
Finally, it works.

**Comment by drpngx** [comment]
Is this still required?

**Comment by JoshData** [comment]
I haven't been following this project since I submitted the PR so I don't know whether it's still correct.

**Comment by drpngx** [comment]
OK, LMK if you want to resolve conflicts and give it another go, or I can close the PR.

**Comment by JoshData** [comment]
I'll close. :)

**Comment by drpngx** [comment]
Thanks!

**Pull request closed without merging**
