### PR TITLE
fix OneDeviceStrategy error

### PR DESCRIPTION
**Pull request by christk1**
fix AttributeError: module 'tensorflow._api.v1.distribute' has no attribute 'OneDeviceStrategy' when running models/official/mnist/mnist.py

### CODE REVIEW

**Comment by christk1** [comment]
I signed it!

**Comment by tfboyd** [comment]
I have a feeling this is a version issue as contrib is not needed.  What version of TensorFlow are you using?  I run tests using the util on TF 1.0 and TF 2.0 on multiple scenarios nightly.  My guess is you have TF 1.13 or maybe earlier.  I forget when the change took place.

**Comment by tfboyd** [comment]
There are tags by version that should work with your version of TensorFlow.  Example below is v1.13.
https://github.com/tensorflow/models/tree/v1.13.0

**Comment by christk1** [comment]
i am using master version and tf.distribute.OneDeviceStrategy is imported only after r1.14rc

**Comment by tfboyd** [comment]
It may take me time to test the RC and to be honest I might not get time.  I thought it was cut well after these changes occurred.   I would use the tagged version for 1.13 above as that used contrib.  We are removing contrib from the examples and adding it back will break the nightly tests as we run both TF 2.0 and TF 2.0 on the same code.  If I get a chance to test with the RC I will report back.

**Comment by tfboyd** [comment]
Or you can install tf-nightly and that will fix the issue.  
https://pypi.org/project/tf-nightly-gpu/

**Comment by guptapriya** [comment]
Yes, we are trying to keep models working with TF nightly, so it's possible the latest version does not work with older versions of TF. Should this PR be closed?

**Pull request closed without merging**
