### PR TITLE
format question fix

### PR DESCRIPTION
**Pull request by vra**
1. change `sharded` to `shared`
2. update shell output according code.

### CODE REVIEW

**Comment by drpngx** [comment]
"sharded" is intentional, it just means split or in multiple partitions.

**Comment by vra** [comment]
@drpngx OK I see, sorry for the inconvenience. How about the second  modification about `.`? I read the code and there is code about putting a `.`. Would you please check it? Thanks. ;)

**Comment by drpngx** [comment]
Are you sure there's no period at the end? It makes a difference to the score. From the output, it looks like the period is a token in the statistical model, because the 2nd candidate doesn't have it. You can't remove it just like that, or it will change the ranking & score. Makes sense?

**Comment by vra** [comment]
You mean the period is just like a word and it's generated by deep learning model? It seems reasonable. So I will close this issue and great thanks for your explanation.

**Comment by drpngx** [comment]
Yes, exactly! You're welcome.

**Pull request closed without merging**
