### PR TITLE
Update optimizer

### PR DESCRIPTION
**Pull request by yhliang2018**
Update optimizer from SGD to Adam for recommendation model, as the name scope issue is fixed in dist strategy.

### CODE REVIEW

**Comment by robieta** [comment]
Do you need to specify the extra Adam parameters?

**Comment by yhliang2018** [comment]
I don't think so, based on the mlperf implementation.

**Comment by karmel** [comment]
MLPerf uses a different library, which may have different defaults-- have you checked that they are the same?

**Comment by yhliang2018** [comment]
Yes, they use the same default values.

**Pull request merged**
