### PR TITLE
Move the research models into a research subfolder

### PR DESCRIPTION
**Pull request by nealwu**
Because the models repository is growing well past what the TensorFlow team can maintain (currently housing 36 top-level folders), we will be making a major restructure of the models repository:

- First, we will be starting an official, supported collection of models in the repo. These models will be implemented with high-level TensorFlow APIs, fast performance, and other best practices that we think newer TensorFlow users should see. The first few models are already available [here](https://github.com/tensorflow/models/tree/master/official).

- Second, we will be moving all of the current models in the repository to a subfolder called 'research'. This will clean up the repository significantly by cutting down the number of top-level folders.

Moving forward, the TensorFlow team will only support issues/PRs on the official models. For the research models we encourage the individual researchers to support them, but we cannot guarantee support.

Unfortunately, the main pain of this restructure is that all existing links to models within the repo will be broken. For those of you who own models in the repo, we know that it will take some effort to correct all of your links, but we hope you'll help us work to quickly get to a cleaner models repository for our users.

### CODE REVIEW

**Comment by jhseu** [comment]
Please update CODEOWNERS

**Comment by nealwu** [comment]
@vikeshkhanna The object detection blog post links have been fixed: https://research.googleblog.com/2017/06/supercharge-your-computer-vision-models.html. Still waiting on the open source blog people to fix that version.

If you notice other blog posts that need to be fixed (especially popular ones), let us know.

**Comment by cshallue** [comment]
@nealwu here's another blog post that needs fixing (2 links). What's the way to go about that?

https://research.googleblog.com/2016/09/show-and-tell-image-captioning-open.html

**Comment by nealwu** [comment]
Hey Chris, thanks for checking on this. Sending you a message internally.

**Comment by panyx0718** [comment]
LGTM

A blog post that needs to fix
https://research.googleblog.com/2016/08/text-summarization-with-tensorflow.html

See the link in quote "We hope this release can also serve a"

**Comment by nealwu** [comment]
@panyx0718 Thanks. Added it to our list.

**Comment by nealwu** [comment]
@panyx0718 Fixed now!

**Comment by alensaqe** [comment]
Any chance that you will make Object Detection officially supported model?

**Pull request merged**
