### PR TITLE
Remove broken links in detection model zoo.

### PR DESCRIPTION
**Pull request by pkulzc**

### CODE REVIEW

**Comment by Thome** [comment]
Why exactly are those two links not working? Are there any chances those trained models will be available any time soon? The mobilenet one would be particularly helpful. :)

**Comment by pkulzc** [comment]
We will officially release some models trained on OID v4 in next PR. It will happen soon!

**Comment by derekjchow** [comment]
LGTM!

**Comment by pkulzc** [comment]
Thanks Derek!

**Comment by Thome** [comment]
> We will officially release some models trained on OID v4 in next PR. It will happen soon!

Sweet, thanks! Is there an ETA on that?

**Comment by pkulzc** [comment]
> > We will officially release some models trained on OID v4 in next PR. It will happen soon!
> 
> Sweet, thanks! Is there an ETA on that?

Should be done in a week or two.

**Comment by yuekaizhang** [comment]
> > > We will officially release some models trained on OID v4 in next PR. It will happen soon!
> > 
> > 
> > Sweet, thanks! Is there an ETA on that?
> 
> Should be done in a week or two.

Come on! It's March now!

**Comment by pkulzc** [comment]
Model zoo has already been updated(https://github.com/tensorflow/models/tree/master/research/object_detection#feb-11-2019).

**Pull request merged**
