### PR TITLE
Variational Autoencoder generate() function fixed (z fed in rather th…

### PR DESCRIPTION
**Pull request by jo8hua**
…an z_mean)

A follow on to a previous update to remove external dependencies from the autoencoder models, and to solve [the following issue](https://github.com/tensorflow/models/issues/1199#issuecomment-289022533). Below is a sample image created from the output of the generate function. 

img1

### CODE REVIEW

**Comment by nealwu** [comment]
@snurkabill could you review?

**Comment by snurkabill** [comment]
ok seems good to me

**Comment by nealwu** [comment]
OK great. Merging.

**Comment by jo8hua** [comment]
Great! Thanks.

**Pull request merged**
