### PR TITLE
added script requested from #3362

### PR DESCRIPTION
**Pull request by Josh-Payne**
This commit adds the script requested from #3362 for converting images to MNIST-format numpy arrays and includes documentation for use. A user can now call `$ python convert_npy.py --image "example5.png example3.png" --batch True --output examples` to generate a file identical to examples.npy, though the pixel values are reversed because the MNIST numbers are white with black background. Also fixed a typo in the readme.

### CODE REVIEW

**Comment by Josh-Payne** [comment]
I signed it!

**Comment by karmel** [comment]
Thanks for the PR. A couple of high-level questions before we review in detail:

1. MNIST is a relatively constrained model, and it seems less likely that people would want to convert their own images for use with MNIST as opposed to, for example, ResNet. Before we provide and maintain a script to do so, it's important to us to assess whether this use case is frequent enough to require a custom solution outside of the guides offered on StackOverflow for converting images to arrays. Have you encountered others having the same problem? It might be better to put it on StackOverflow or a similar place for housing recipes if this isn't a frequent use case.

2. If this is a common use case, it would make sense to have a script that converts images to arrays, but this script seems fairly complex for what it does-- for example, using both Numpy and built-in arrays; iterating through each pixel of the image; having command line options to batch or not batch; etc. Can you simplify some of the code here to just take in an image and convert to a numpy array as efficiently as possible?

**Comment by Josh-Payne** [comment]
Hello @karmel, thanks for the evaluation! As for the use case, my particular motivation for creating this script was to extend the model for doing OCR and recognizing geometric shapes for a UAV competition. This is one of the few models I've found out there that uses the TF.Estimator on a small dataset like the MNIST, so I wanted to use it as a template. 

If you do decide it would be useful, I've trimmed it down considerably and removed some of the command line options. Because the pixels are arranged row-wise in the MNIST, the iterators substitute for having to do a numpy.flip. Thanks again for reviewing this!

**Comment by karmel** [comment]
Thanks @Josh-Payne -- that sounds like a fairly specific use case, so this is probably best housed elsewhere for now. If others end up on this page and it turns out there are many use cases, we can re-open.

As a side note, using built-in numpy functions for array manipulation are generally much faster and more efficient than iterating through an array. Might be a fun exercise to try timing this script with the for loops versus using only numpy operations to see what the delta is.

**Pull request closed without merging**
