### PR TITLE
Add the basic-classification notebook.

### PR DESCRIPTION
**Pull request by MarkDaoust**
The broken image will be fixed when we publish the site.

preview link:

https://colab.sandbox.google.com/github/markdaoust/models/blob/basic-classification/samples/core/get_started/basic_classification.ipynb

### CODE REVIEW

**Comment by lamberta** [comment]
Need to publish https://tensorflow.org/images/fashion-mnist-sprite.png

**Comment by MarkDaoust** [comment]
working on it cl/200419799

**Comment by lamberta** [comment]
Updated original with image caption/license. Can you use that version?

**Comment by MarkDaoust** [comment]
> Updated original with image caption/license. Can you use that version?

Patched.

**Comment by lamberta** [comment]
Add MIT license: https://github.com/MarkDaoust/models/pull/3

**Pull request merged**
