### PR TITLE
eager.ipynb

### PR DESCRIPTION
**Pull request by MarkDaoust**
Set private_outputs = true

Add more code examples, demonstrating things running after being defined.

### CODE REVIEW

**Comment by lamberta** [comment]
Do you have a "staging" link handy? I can never remember the colab url format for git commits

**Comment by MarkDaoust** [comment]
https://colab.sandbox.google.com/github/markdaoust/models/blob/get_started/samples/core/get_started/eager.ipynb

**Comment by lamberta** [comment]
I can't edit here, so created a pul request on your repo: https://github.com/MarkDaoust/models/pull/1
PTAL

**Comment by MarkDaoust** [comment]
Hey @nealwu,

What's missing for @lamberta to be able to review PR's to this directory?
I've added him to "CODEOWNERS", but it doesn't seem like it worked.

Thanks.

**Comment by karmel** [comment]
Hm. That's weird. He appears to be a public member of TF, and that's all that should be required. @lamberta, did you click the Approve button in the web UI for this PR, or through some other means? Can you try again?

**Comment by karmel** [comment]
I have no idea. Your check mark is different, too. Who is an expert in Github permissions? @gunan , do you know why @lamberta is not able to fully approve?

**Comment by lamberta** [comment]
Hey @karmel,
The tensorflow/tensorflow repo works as expected for me, this one is giving me different behavior. I can select approve through the web UI only if I go to "Files Changed" > "Review Changes" (dropdown) > "Approve".
On this conversation page, there's no review button or anything. And my name doesn't show when you try to request me as a reviewer (only on this repo, tf/tf works as expected.

This PR was also started a while ago. Maybe there's a bug there? Can try a new PR.

**Comment by gunan** [comment]
It should be resolved now.

**Comment by lamberta** [comment]
Looks right. Thanks, @gunan !

**Pull request merged**
