### PR TITLE
Revert "tf_upgrade_v2 on resnet and utils folders. (#6154)"

### PR DESCRIPTION
**Pull request by goldiegadde**
This reverts commit d6b2b83c0eb668085ecf4045178d210e7bc69892.

### CODE REVIEW

**Comment by goldiegadde** [comment]
> Thanks, Goldie-- can we then create a branch that is synced to the prior commit (right before this rollback) for v2 for now?

@tfboyd , so that  he is informed.

**Comment by goldiegadde** [comment]
> > Thanks, Goldie-- can we then create a branch that is synced to the prior commit (right before this rollback) for v2 for now?
> 
> @tfboyd , so that he is informed. Yes I think we can do that.

**Comment by tfboyd** [comment]
Why it was decided to stop tagging this feels crazy.

**Comment by tfboyd** [comment]
@karmel   I want to test the following
- I want to main branch to be compat.v1 or pure TF 1.0.  So we can test TF 1.0 with compat along with some TF 2.0 testing.
- a separate branch where we are doing V2 that will cannot exist at the same time easily.

**Comment by tfboyd** [comment]
Keep in mind the README says this.

The master branch of the models are in development, and they target the nightly binaries built from the master branch of TensorFlow. We aim to keep them backwards compatible with the latest release when possible (currently TensorFlow 1.5), but we cannot always guarantee compatibility.

**Comment by karmel** [comment]
@tfboyd -- I think we resolved offline, but sounds like this is a problem with an older version, and the current Models HEAD works with TF 1.x HEAD, in which case a rollback/branch is not necessary. Sorry for the thrash on this, @goldiegadde

**Comment by f23505106** [comment]
class ExamplesPerSecondHook(tf.estimator.SessionRunHook):
AttributeError: module 'tensorflow.python.estimator.api.estimator' has no attribute 'SessionRunHook'

**Pull request merged**
