### PR TITLE
Suggestions about print and initializer.

### PR DESCRIPTION
**Pull request by linrio**
1. 

In _models/autoencoder/AdditiveGaussianNoiseAutoencoderRunner.py :46_
Changing
   ```
 # Display logs per epoch step
    if epoch % display_step == 0:
        print "Epoch:", '%04d' % (epoch + 1), \
            "cost=", "{:.9f}".format(avg_cost)

print "Total cost: " + str(autoencoder.calc_total_cost(X_test))

```
to
```
    # Display logs per epoch step
    if epoch % display_step == 0:
        print("Epoch:", '%04d' % (epoch + 1), \
            "cost=", "{:.9f}".format(avg_cost))

print("Total cost: " + str(autoencoder.calc_total_cost(X_test)))
```
Also for _models/autoencoder/AutoencoderRunner.py , MaskingNoiseAutoencoderRunner.py and VariationalAutoencoderRunner.py_

2. 
In _models/autoencoder/autoencoder_models/Autoencoder.py :24_
Changing
    ` init = tf.initialize_all_variables()`
to
    `init = tf.global_variables_initializer()`

Also for _models/autoencoder/autoencoder_models/DenoisingAutoencoder.py and models/autoencoder/autoencoder_models/VariationalAutoencoder.py ._

Because 
**tf.initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use tf.global_variables_initializer instead.**

### CODE REVIEW

**Comment by linrio** [comment]
@googlebot I signed it!

**Comment by nealwu** [comment]
Hi @linrio, your pull request has a ton of changes other than the ones you described. Can you remove the excess changes and ping me again when you've narrowed it down? Thanks.

**Comment by nealwu** [comment]
Adding @ebrevdo since it looks like you're the code author.

**Comment by ebrevdo** [comment]
None of the rdefs code is related to this change. Please revert it.

**Comment by nealwu** [comment]
It looks like all the code is `experimental/rdefs` rather than the changes @linrio described. Going to close this PR in that case.

**Pull request closed without merging**
