### PR TITLE
Fix eval_config field - eval_interval_secs not working

### PR DESCRIPTION
**Pull request by bleqdyce**
I think eval_interval_secs is originally designed to be passed as one of EvalSpec parameter - throttle_secs, which defines the frequency of saving checkpoint and evaluation.
Because setting eval_interval_secs is not working, there is no other way to change the frequency of evaluation.
Therefore, I simply parse eval_interval_secs from eval config and pass it to EvalSpec as a parameters to complete this functionality.

### CODE REVIEW

**Comment by ruifm** [comment]
This is a must have imo. Please merge it!

**Comment by pkulzc** [comment]
Could you please resolve the conflicts ?

**Comment by thusinh1969** [comment]
Gents,

Have this been fixed and applied fully in latest tensorflow object detection repo so we can re-download it ? This is killing us...

Thanks,
Steve

**Comment by Magikis** [comment]
Any progress with the issue?

**Comment by bleqdyce** [comment]
@googlebot I consent.

**Comment by piercus** [comment]
@googlebot I consent.

**Comment by jaeyounkim** [comment]
@pkulzc Please review this pull request.

**Comment by Mathieu4141** [comment]
Hi !
Is there a reason why this is not yet merged ?

**Pull request closed without merging**
