### PR TITLE
correct the percentage logs in slim_walkthrough.ipynb

### PR DESCRIPTION
**Pull request by shallinlin**
Correct the format of the percentages in slim_walkthrough.ipynb.
The probability is shown as percentage thus should be scaled correctly.

### CODE REVIEW

**Comment by shallinlin** [comment]
I signed it!

**Comment by nealwu** [comment]
@shallinlin This looks good to me. Can you provide me with some before/after output to verify that this is a valid change?

**Comment by shallinlin** [comment]
Here is the screen-capture for the output before and after changes:
screen shot 2017-05-09 at 8 31 35 pm
screen shot 2017-05-09 at 8 31 48 pm
screen shot 2017-05-09 at 8 33 04 pm
screen shot 2017-05-09 at 8 33 14 pm

**Comment by nealwu** [comment]
Looks good. Thanks!

**Pull request merged**
