### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by ywryoo**
Add case for compiling ops if tensorflow was compiled from source using gcc >= 5.0

### CODE REVIEW

**Comment by ywryoo** [comment]
I have signed it :)

**Comment by nealwu** [comment]
Did that flag break the compilation for you @ywryoo?

**Comment by nealwu** [comment]
I would prefer to add a shorter comment at the end of the parenthetical comment explaining the flag. Something like: "If you compiled TensorFlow from source using g++ 5.0 or later, you won't need the flag."

**Comment by ywryoo** [comment]
Hi @nealwu, thanks for response! The reason I wrote entire code again was for people who are not familiar with English. They tend to copy-and-paste code without reading any sentences. However I agree that one line of comment would be clearer than writing whole code again. Would it be okay to add commit for that change in here? This is my first pull request so I am quiet nervous to make any changes.

**Comment by nealwu** [comment]
Yep you can add another commit here to that effect. Does the command fail if you include the flag in your situation (having compiled TensorFlow from source with g++ >= 5.0)?

**Comment by ywryoo** [comment]
Yes. I was on Ubuntu Desktop 16.04.2 and compiled tensorflow from source for optimization. g++ command run without error, but `python word2vec_optimized.py ...` failed because of the flag. So I wanted to clarify the situation for people who will get same error :)

**Comment by ywryoo** [comment]
I've updated explanation as suggestion.

**Comment by nealwu** [comment]
I'm assuming you didn't use the extra `-cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"` flag mentioned here: https://www.tensorflow.org/install/install_sources#install_the_pip_package. I have to admit though, it's not very clear on where to add it -- you actually need to include it in the `bazel build` command several lines above. Going to file a documentation bug for this.

In any case, I'll edit your comment so that it works for either situation, and then we can go ahead and merge.

**Comment by nealwu** [comment]
Thanks @ywryoo!

**Pull request merged**
