### PR TITLE
fix batch_size in transformer_main.py

### PR DESCRIPTION
**Pull request by theJiangYu**
fix batch_size in transformer_main.py which causes ResourceExhaustedError: OOM during training Transformer models using models/official/transformer

### CODE REVIEW

**Comment by robieta** [comment]
Good catch!
Can you change it to
```
params["batch_size"] = (flags_obj.batch_size or (
    params["default_batch_size_tpu"] if params["use_tpu"] 
    else params["default_batch_size"]))
```
(so it will pass lint tests)

**Comment by theJiangYu** [comment]
Format change is done. Thanks, Taylor (robieta) !

**Comment by robieta** [comment]
Looks like the linter is still complaining. If you run `official/utils/testing/scripts/presubmit.sh` with no arguments it will lint the whole repo.

**Comment by theJiangYu** [comment]
Removed trailing white space etc, and Linting test passed on my local machine. Please try again @robieta

**Pull request merged**
