### PR TITLE
Support for non-TYPE_3BYTE_BGR images in Java project

### PR DESCRIPTION
**Pull request by chsin**

### CODE REVIEW

**Comment by chsin** [comment]
@asimshankar

**Comment by chsin** [comment]
I signed it!

**Comment by asimshankar** [comment]
@sjamesr - mind taking a look?

**Comment by chsin** [comment]
@sjamesr, @asimshankar -- it seems there needs to be approval from reviewers with right access for this to be merged?

**Comment by chsin** [comment]
@MarkDaoust: still need to be approved by someone with write access

**Pull request merged**
