### PR TITLE
1. update to tf2.x for deep_speech

### PR DESCRIPTION
**Pull request by moneypi**
2. compatible with tf1.14

# Description

> :memo: Please include a summary of the change. 
>  
> * Please also include relevant motivation and context.  
> * List any dependencies that are required for this change.  

## Type of change

For a new feature or function, please create an issue first to discuss it
with us before submitting a pull request.

Note: Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update
- [x] TensorFlow 2 migration
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] A new research paper code implementation
- [ ] Other (Specify)

## Tests

> :memo: Please describe the tests that you ran to verify your changes.
>  
> * Provide instructions so we can reproduce.  
> * Please also list any relevant details for your test configuration.  

**Test Configuration**:

## Checklist

- [x] I have signed the [Contributor License Agreement](https://github.com/tensorflow/models/wiki/Contributor-License-Agreements).
- [x] I have read [guidelines for pull request](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).
- [x] My code follows the [coding guidelines](https://github.com/tensorflow/models/wiki/Coding-guidelines).
- [x] I have performed a self [code review](https://github.com/tensorflow/models/wiki/Code-review) of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by saberkun** [comment]
@jaeyounkim We have marked this deep speech model as deprecation candidate and would remove it in Q2. Do we still want to migrate it? Or the contributor can be an maintainer so that we can keep this model?

**Comment by jaeyounkim** [comment]
@saberkun Deep speech 2 is a good model. If this code works well, I would like to suggest to move deep_speech to the community directory or keep it in the research directory if we can get more contribution to make it TF 2 native.

**Comment by moneypi** [comment]
> @saberkun Deep speech 2 is a good model. If this code works well, I would like to suggest to move deep_speech to the community directory or keep it in the research directory if we can get more contribution to make it TF 2 native.

I will update the model to TF 2 native API next PR.

**Comment by saberkun** [comment]
@moneypi Thanks.
@jaeyounkim Will find some people to test the PR and follow up if necessary. Thanks

**Comment by moneypi** [comment]
How long should we wait more?

**Comment by saberkun** [comment]
@jaeyounkim Do you find any student to test this out?
@moneypi Are you able to run the model to reach the reference accuracy?

**Comment by jaeyounkim** [comment]
@moneypi We will test your PR this week.

**Comment by kyscg** [comment]
I've tested both the TF2 and TF1 versions for this code and it works well. It reaches reference accuracy and I think it will work for the time-being. However, the code is not yet native TF2 and further work needs to be done.

**Comment by moneypi** [comment]
@kyscg Great.
Can you tell me what kind of GPU do you use to train the model ?

**Comment by jaeyounkim** [comment]
@kyscg Thank you for testing the PR.
@moneypi  Thank you for your PR. I hope you can help us to make it native TF 2 code.

**Pull request merged**
