### PR TITLE
Use more warmup steps for 96 core tests

### PR DESCRIPTION
**Pull request by haoyuz**
Increase the number of warmup steps for 96 core platforms. Hope this can stabilize the reported performance.

### CODE REVIEW

**Comment by guptapriya** [comment]
why not just do more warmup steps in all cases?

**Comment by haoyuz** [comment]
> why not just do more warmup steps in all cases?

I think that should be good as well; just a minor point, getting stable performance in a short period of time is also desirable so we might want to eventually figure out the slowness on 96. Keeping tests on 64 or DGX-1 short can also save resources a little bit 😺

**Comment by guptapriya** [comment]
> > why not just do more warmup steps in all cases?
> 
> I think that should be good as well; just a minor point, getting stable performance in a short period of time is also desirable so we might want to eventually figure out the slowness on 96. Keeping tests on 64 or DGX-1 short can also save resources a little bit 😺

I am fine either way, check with @tfboyd as he is the expert on the benchmarks.

**Comment by haoyuz** [comment]
> Let's make a new test that does the delayed or longer measurement. That way we have a constant comparison on any system. Just do it for 8-GPUs. tweaked / non-tweaked if desired and only fp16+xla as that is where it matters. `tweaked_delay_measure` or something and try to keep it short.

Added tests, PTAL. Thanks for the reviews!

**Pull request merged**
