### PR TITLE
Correct 404 link for object detection tutorial

### PR DESCRIPTION
**Pull request by andrea-garritano**
# Description

> :memo: The previous url led to 404 errors. This commit uses the correct URL.

## Type of change

For a new feature or function, please create an issue first to discuss it
with us before submitting a pull request.

Note: Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Documentation update
- [ ] TensorFlow 2 migration
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] A new research paper code implementation
- [ ] Other (Specify)

## Checklist

- [X] I have signed the [Contributor License Agreement](https://github.com/tensorflow/models/wiki/Contributor-License-Agreements).
- [X] I have read [guidelines for pull request](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).
- [X] My code follows the [coding guidelines](https://github.com/tensorflow/models/wiki/Coding-guidelines).
- [X] I have performed a self [code review](https://github.com/tensorflow/models/wiki/Code-review) of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by tylerganter** [comment]
This seems like an easy one and done. Any reason it hasn't been merged yet?

**Comment by andrea-garritano** [comment]
> This seems like an easy one and done. Any reason it hasn't been merged yet?

I'm waiting some reviewer to approve my PR.

Can @saberkun accept this?

**Comment by tylerganter** [comment]
@vighneshbirodkar could you approve this?

**Review by vighneshbirodkar — APPROVED** [review]

**Comment by vighneshbirodkar** [comment]
@tylerganter @andrea-garritano I don't have commit access to this repo.

**Comment by andrea-garritano** [comment]
> @tylerganter @andrea-garritano I don't have commit access to this repo.

@vighneshbirodkar has been added as a collaborator on the repository.

Let me know if you have the commit access.
Thanks

**Comment by vighneshbirodkar** [comment]
@andrea-garritano That doesn't help. For approvals you this someone with commit access to *this* repo. @pkulzc or @tombstone can help.

**Comment by tylerganter** [comment]
Could someone approve this???? It's honestly a shame that these PRs are just sitting here ignored. Especially something as trivial as this. It really discourages collaboration and contribution from the community.

**Pull request merged**
