### PR TITLE
Lstm object detection improvements

### PR DESCRIPTION
**Pull request by richardbrks**
I am interested in getting this project setup up to have an easier walkthrough from tfrecord creation to having a model running on android, specifically for the SSD Interleaved v2 model. These updates are steps in that direction:

- replaces `google3.pylib` module with `tf` and `absl` (321b085)
- adds example pipeline config for SSD Interleaved v2 model (231e65e)
- removes incorrect and unused tfrecords creation in unittest (ae5b330)
- corrects docstrings (e5810f9)
- adds frozen graph exporter (181119e)
- adds tflite model exporter (3f5de09)
- adds scripts to test tflite model (b613257)

### CODE REVIEW

**Comment by richardbrks** [comment]
added model export documentation (729071f)

**Comment by yongzhe2160** [comment]
Thanks. I had a few comments, otherwise LGTM. Also it's better to rename the export_tflite_graph* files to export_tflite_lstd_graph* because there is already export_tflite_ssd_graph*

**Comment by richardbrks** [comment]
Thanks for the comments. I believe I've handled everything you've addressed. I was unsure which years to update for the copyrights, so I just updated the year to 2019 for all of the new files that I added.

**Comment by richardbrks** [comment]
The keys in the Example specified in `_create_tf_record()` differ from what is expected in [TFSequenceExampleDecoder](https://github.com/tensorflow/models/blob/03b4a0af1b71d98656b0c471939b3e6d0d5e4510/research/lstm_object_detection/inputs/tf_sequence_example_decoder.py#L89). I would have corrected the keys, but I noticed that the method was never used, so I decided to delete it instead.

**Comment by dreamdragon** [comment]
Thanks for your contribution!

**Comment by UmarSpa** [comment]
Any chance you can provide some documentation on how to build the tf records for this model ?
@rrtaylor @dreamdragon

**Pull request merged**
