### PR TITLE
add skipthought to tensorflow models repo

### PR DESCRIPTION
**Pull request by knathanieltucker**
https://arxiv.org/abs/1506.06726

### CODE REVIEW

**Comment by nealwu** [comment]
@martinwicke is this a model we're interested in adding?

**Comment by martinwicke** [comment]
Is this the model I just uploaded checkpoints for?

**Comment by nealwu** [comment]
@martinwicke not sure what you mean. I've been going through the pull requests in this repository and encountered this new model, so I thought I'd check whether you think it's worth including.

**Comment by martinwicke** [comment]
@knathanieltucker turns out we have an implementation of this model that I have just uploaded checkpoints for. It comes with some extra bells and whistles, so we'll merge that instead. 

I'm sorry about the unfortunate timing.

**Comment by knathanieltucker** [comment]
Sigh, yeah no problem. I should have poked you before. 

Hey Neal! Small world ;p. I'll ping you on messenger

**Pull request closed without merging**
