### PR TITLE
Adding automatic mixed precision training (via graph rewrite) support to BERT pretraining & fine-tuning tasks

### PR DESCRIPTION
**Pull request by vinhngx**
Automatic Mixed Precision for TensorFlow has recently been introduced:
https://medium.com/tensorflow/automatic-mixed-precision-in-tensorflow-for-faster-ai-training-on-nvidia-gpus-6033234b2540

In continuation of https://github.com/tensorflow/models/pull/7419, this PR adds automatic mixed precision training to  BERT pretraining & fine-tuning tasks via setting the flag combo `--dtype=fp16 --fp16_implementation=graph_rewrite`.

For example:

```
python3 run_pretraining.py --dtype=fp16 --fp16_implementation=graph_rewrite
python3 run_classifier.py --dtype=fp16 --fp16_implementation=graph_rewrite
python3 run_squad.py --dtype=fp16 --fp16_implementation=graph_rewrite
```

### CODE REVIEW

**Comment by vinhngx** [comment]
Hi @tfboyd I don't see perfzero test configs for BERT pretraining tasks yet.  If you define this, we can add test configs for the 8/16-GPU AMP run and can verify the expected results at our end (though it probably will take up to a week to run end-to-end on a DGX-1, and 3.5 days on a DGX-2)

**Comment by vinhngx** [comment]
> 
> 
> can we avoid overriding squad_model.optimizer many times?
> squad_model.optimizer = (
> tf.keras.mixed_precision.experimental.LossScaleOptimizer(
> squad_model.optimizer, loss_scale=common_flags.get_loss_scale()))
> if FLAGS.fp16_implementation == 'graph_rewrite':
> squad_model.optimizer = tf.train.experimental.enable_mixed_precision_graph_rewrite(
> squad_model.optimizer)

Hi @saberkun, I made a comment in the code regarding this:
      # Note: when flags_obj.fp16_implementation == "graph_rewrite", dtype as
      # determined by flags_core.get_tf_dtype(flags_obj) would be 'float32'
      # which will ensure tf.compat.v2.keras.mixed_precision and
      # tf.train.experimental.enable_mixed_precision_graph_rewrite do not double
      # up.

Basically, Keras FP16 is activated only when `--dtype=fp16` and `--fp16_implementation=casting`. 

Note that with  `--dtype=fp16` and `--fp16_implementation=graph_rewrite`, use_float16 is False so the below path will not be executed:
 ```    if use_float16:
      # Wraps optimizer with a LossScaleOptimizer. This is done automatically
      # in compile() with the "mixed_float16" policy, but since we do not call
      # compile(), we must wrap the optimizer manually.
      squad_model.optimizer = (
          tf.keras.mixed_precision.experimental.LossScaleOptimizer(
              squad_model.optimizer, loss_scale=common_flags.get_loss_scale()))
```

**Comment by saberkun** [comment]
Hi Vinh,

Since this PR is straightforward, I would like to help it merge asap. We will have a few code refactor works later, will be no-op. 
Hope it sounds good to you. I will merge this PR.

**Comment by saberkun** [comment]
Note that, we do not have any tests to cover benchmark test cases, like: benchmark_8_gpu_amp
Please manually run with perfzero. As they do not affect any critical path, merging is fine

**Pull request merged**
