### PR TITLE
resnet fine tuning

### PR DESCRIPTION
**Pull request by zacwellmer**
warm start a resent with all but the dense layer and only update the final layer weights when fine tuning

### CODE REVIEW

**Comment by zacwellmer** [comment]
I signed it!

**Comment by karmel** [comment]
Thanks, @zacwellmer -- I like this as an example of how to use WarmStartSettings. That said, it's not clear to me that this is a generally useful change, and it does complicate an already complicated model. Can you clarify the motivation here? cc @robieta

**Comment by zacwellmer** [comment]
As the resnet project stands there does not exist a way to:
1) load a pretrained model with a different number of output classes
2) freeze earlier layers for fine tuning
Both of the above cases are key features to users who want to implement a resnet on their own datasets. 

I'm open to approaching the above two cases in a different way if you have any other ideas. My original idea was to use the same approach that the [inception](https://github.com/tensorflow/models/tree/master/research/inception) repo uses for fine tuning. However, that repo makes heavy use of tf slim which isn't the case in the resnet official repo. In the end it seemed best to keep the same flags the same but solve the problem in a  different way.

**Comment by karmel** [comment]
I think the changes you have made seem fine for your use-case, and I would suggest forking the official models and modifying the code as fits your use-case. If you can help us determine that this is a generally useful feature, rather than one that is not much requested, we can include the changes in the official version as well. How does that sound?

**Comment by zacwellmer** [comment]
That sounds good to me. What would you like to see to help you determine if this is a generally useful feature? 

In terms motivation from research: The [DeCAF paper](https://arxiv.org/abs/1310.1531) was one of the earlier works on transfer learning.

In terms of motivations from a practical standpoint: If you passed the pretrained imagenet weights to the pretrained model checkpoint flag and set the fine_tune checkpoint to True. Then trained on a smaller dataset, you could expect better generalization than if you trained on the smaller dataset alone.

**Comment by robieta** [comment]
I am always wary of adding more knobs to an already somewhat unwieldy model. However, this is a very modest change in terms of code complexity, and I think would be of general interest. (Both to fine tune models and as an example of how to "transfer learning-ize" a model.) So my vote would be for adding it. The one request that I would make is to add a blob in the README about what the fine tuning knob is and how to invoke it.

**Comment by karmel** [comment]
That WFM-- @robieta , you can take it from here in that case.

**Comment by zacwellmer** [comment]
I am closing this pull request b/c of issues git config issues and have reopened [here](https://github.com/tensorflow/models/pull/5047)

**Pull request closed without merging**
