### PR TITLE
Fix compatibility for model_builder_test.py

### PR DESCRIPTION
**Pull request by justanhduc**
iteritems -> items

### CODE REVIEW

**Comment by derekjchow** [comment]
Could you do this with [six.iteritems](https://pythonhosted.org/six/#six.iteritems) instead to preserve python 2 compatibility?

**Comment by nealwu** [comment]
@derekjchow does `items()` not fully work in Python 2? I have actually merged a few pull requests converting `iteritems()` to `items()` before so it would be good to know.

**Comment by justanhduc** [comment]
@derekjchow @nealwu ok I will commit again using `six.iteritems`.

**Comment by nealwu** [comment]
@justanhduc no worries, we talked and decided that `.items()` is sufficient here.

**Comment by dyy543182718** [comment]
语言不通想交流都困难,唉!

**Comment by marlazinger200** [comment]
1

**Comment by kaseyriver11** [comment]
@nealwu I believe this issue is also occurring in batcher.py

tensorflow/models/object_detection/core/batcher.py

**Comment by nealwu** [comment]
@kaseyriver11 could you send in a pull request for it?

**Comment by kaseyriver11** [comment]
@nealwu It looks like they included it in one of the updates yesterday. Thanks =)

**Pull request merged**
