### PR TITLE
Fixed Object Detection Colab Tutorial

### PR DESCRIPTION
**Pull request by ucalyptus**
Check https://colab.research.google.com/drive/1b7iIzHw6m9lCcNqR1EMjp_rbu0icIZ-K?usp=sharing for more information.This is the content for this PR.

# Description

On running the given notebook tutorial for object tutorial on Colab I found bugs on two places .
One at the the masking_model plotting , other at the model was not assigned a serving_default signature for the same.
For better understanding of where the issue was, please run the original NB on colab. 
Also solves #8839 

## Type of change

For a new feature or function, please create an issue first to discuss it
with us before submitting a pull request.

Note: Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update
- [ ] TensorFlow 2 migration
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] A new research paper code implementation
- [ ] Other (Specify)

## Tests

> :memo: Please describe the tests that you ran to verify your changes.
>  
> * Provide instructions so we can reproduce.  
> * Please also list any relevant details for your test configuration.  

**Test Configuration**:

## Checklist

- [x] I have signed the [Contributor License Agreement](https://github.com/tensorflow/models/wiki/Contributor-License-Agreements).
- [x] I have read [guidelines for pull request](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).
- [x] My code follows the [coding guidelines](https://github.com/tensorflow/models/wiki/Coding-guidelines).
- [x] I have performed a self [code review](https://github.com/tensorflow/models/wiki/Code-review) of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by ucalyptus** [comment]
cc: @tombstone , @jch1 , @pkulzc

**Comment by forkbabu** [comment]
@tombstone is this fine?

**Comment by tombstone** [comment]
Thanks @ucalyptus. sorry for the delay. Could you rebase with latest changes and update the PR ? The links have been now fixed.

**Comment by ucalyptus** [comment]
@googlebot I consent.

**Comment by ucalyptus** [comment]
@tombstone any issues?

**Comment by tombstone** [comment]
Your PR contains a huge number of other files. Can you fix this and resend ?

**Comment by tombstone** [comment]
@ucalyptus I am closing this PR since its causing issues with the PR bot. Can you send a new one with just the fix to colab ?

**Comment by ucalyptus** [comment]
Ok sure @tombstone

**Pull request closed without merging**
