### PR TITLE
EEG analysis

### PR DESCRIPTION
**Pull request by abhishek-parashar**

### CODE REVIEW

**Comment by abhishek-parashar** [comment]
@googlebot I signed it!

**Comment by abhishek-parashar** [comment]
@googlebot googlebot I signed it!

**Comment by abhishek-parashar** [comment]
@saberkun please review

**Comment by MarkDaoust** [comment]
Hi @abhishek-parashar,

I think the research/ directory is really meant for internal-google-researchers to use for sharing code associated with published research papers.

So I don't think this is the right place for this.

There is a tensorflow/examples repository that you could submit this to, that would be more appropriate.

**Pull request closed without merging**
