### PR TITLE
Update inception model based on tf API changes

### PR DESCRIPTION
**Pull request by lilao**
replace tf.op_scope with tf.name_scope and tf.variable_op_scope with tf.variable_scope; fix the order of arguments for tf.concat; replace tf.mul with tf.multiply.

### CODE REVIEW

**Comment by soupault** [comment]
I'm just curious why hadn't my PR been taken into consideration - https://github.com/tensorflow/models/pull/639 ...

**Comment by martinwicke** [comment]
I hadn't seen it. Support for models/ is best effort, and it does happen that things slip. 

I am sorry.

**Comment by soupault** [comment]
@martinwicke thanks for the feedback, Martin! I understand that it (probably) was a busy time preparing TF 1.0 release.
As long as you are here, may I ask you if there are any plans to add CI testing for models?

**Comment by martinwicke** [comment]
We will make a new repo with models we maintain. models/ will stick around as a place for researchers to open-source their code, but we do not have the bandwidth to provide proper support (incl. CI) for it for now. Of course, any project owner may set up their own testing, and some have done so.

**Pull request merged**
