### PR TITLE
CogMap: import logging

### PR DESCRIPTION
**Pull request by cclauss**
graph_utils.py -- __logging__ is used on lines 454 and 512 but it is never imported.

map_utils.py -- __logging__ is used on line 144 but it is never imported.

### CODE REVIEW

**Comment by cclauss** [comment]
@s-gupta Could I please get your review on these changes?

**Comment by cclauss** [comment]
@nealwu Your thoughts?

**Comment by nealwu** [comment]
Jenkins, test this please.

**Comment by nealwu** [comment]
Jenkins, test this please.

**Pull request merged**
