### PR TITLE
tf.contrib.deprecated elimination bugfix for tf version 12

### PR DESCRIPTION
**Pull request by mrphoenix13**
according to #784  after upgrading tf version to 0.12 tf.contrib.deprecated has been eliminated. This pull request fixes the code to make it work with tf version 0.12.

### CODE REVIEW

**Comment by YuMS** [comment]
`tf.scalar_summary` is also deprecated in TensorFlow 0.12.1, these are some warnings for `tf.scalar_summary`


```
WARNING:tensorflow:From ptb_word_lm.py:341 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed a
fter 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatic
ally de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no long
er supported.
```

**Comment by MartinThoma** [comment]
See https://github.com/MartinThoma/algorithms/commit/38ce1f87d6e4396cde64fe831c2ead2507781270 for the changes which need to be made.

**Comment by BSVogler** [comment]
@MartinThoma Can you merge it with the tensorflow:master please?
Fond your fix via google as the current version does not run by missing the strides parameter.

**Comment by MartinThoma** [comment]
@BSVogler Sorry, I was busy the last days. Here is the pull request which seems to fix the problems https://github.com/tensorflow/models/pull/962

**Pull request merged**
