### PR TITLE
YOLOv4-tiny: Adding config and updating YOLO's README

### PR DESCRIPTION
**Pull request by jacob-zietek**
# Description

This PR adds a new YOLOv4-tiny config that achieves 21.21AP. It also updates the YOLO project's README.md to include metrics and a place for checkpoints.

## Type of change

- [x] A new research paper code implementation

## Checklist

- [x] I have signed the [Contributor License Agreement](https://github.com/tensorflow/models/wiki/Contributor-License-Agreements).
- [x] I have read [guidelines for pull request](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).
- [x] My code follows the [coding guidelines](https://github.com/tensorflow/models/wiki/Coding-guidelines).
- [x] I have performed a self [code review](https://github.com/tensorflow/models/wiki/Code-review) of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by fyangf — COMMENTED** [review]
Need to update the path to remove `beta` so it can be merged.

**Comment by jacob-zietek** [comment]
@fyangf To confirm, you'd like me to move the changes from 

`official/vision/beta/projects/yolo/README.md => official/projects/yolo/README.md`

and

`official/vision/beta/projects/yolo/configs/experiments/yolov4/detection/yolov4_tiny_416_tpu.yaml => official/projects/yolo/configs/experiments/yolov4/detection/yolov4_tiny_416_tpu.yaml`?

**Comment by fyangf** [comment]
> @fyangf To confirm, you'd like me to move the changes from
> 
> `official/vision/beta/projects/yolo/README.md` => `official/projects/yolo/README.md`
> 
> and
> 
> `official/vision/beta/projects/yolo/configs/experiments/yolov4/detection/yolov4_tiny_416_tpu.yaml` => `official/projects/yolo/configs/experiments/yolov4/detection/yolov4_tiny_416_tpu.yaml`?

Yes exactly.

**Comment by jacob-zietek** [comment]
@fyangf This should work now, please let me know if you need anything else. Thank you!

**Review by fyangf — DISMISSED** [review]

**Comment by jacob-zietek** [comment]
@fyangf Is there anything you need on my end?

**Comment by fyangf** [comment]
> @fyangf Is there anything you need on my end?

Can you sync to master branch again and resolve the conflict? There are some new changes to the README file.

**Comment by jacob-zietek** [comment]
@fyangf All done, thanks!

**Review by fyangf — APPROVED** [review]

**Comment by jacob-zietek** [comment]
Hi @fyangf, is there anything else I need to do to get this merged?

**Comment by jacob-zietek** [comment]
Hi @fyangf. Anything else I'd need to do to get this merged?

**Comment by laxmareddyp** [comment]
Hi @jacob-zietek,

Could you please sync to head and push it again.It seems something went wrong internally.

I apologize for the duplication of effort.

Thanks.

**Comment by jacob-zietek** [comment]
I just synced it, thanks. @laxmareddyp

**Pull request merged**
