### PR TITLE
Spatial Transformer batches and flexible outputs

### PR DESCRIPTION
**Pull request by psycharo**
* Modified the way the output size is specified.
* Added support for batches of inputs.

### CODE REVIEW

**Comment by psycharo** [comment]
I signed it!

**Comment by elezar** [comment]
@psycharo Just a note. This change has broken the examples that are included with the model. These still specify the output size using `downsample_factor`. I will see if I can get a PR in with the changes.

**Comment by daviddao** [comment]
@elezar Also the corresponding [README](https://github.com/tensorflow/models/blob/master/transformer/README.md#parameters) is not up to date anymore. Do you mind updating the parameter description with #155 ?

**Comment by elezar** [comment]
Sure. I thought I did, but I might have forgotten to push the latest
commit. Will do that tomorrow morning (I'm afk for the evening).

On Thu, 26 May 2016, 17:49 David Dao, <notifications@github.com> wrote:

> @elezar <https://github.com/elezar> Also the corresponding README
> <https://github.com/tensorflow/models/blob/master/transformer/README.md#parameters>
> is not up to date anymore. Do you mind updating the parameter description
> with #155 <https://github.com/tensorflow/models/pull/155> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tensorflow/models/pull/57#issuecomment-221911697>
>
-- 
Evan Lezar
www.evanlezar.com

**Comment by daviddao** [comment]
No, I was wrong. You already included it in your PR! Thanks a lot :) - your commit looks good.

**Pull request merged**
