### PR TITLE
_strict_random_crop_image: fix mask slice

### PR DESCRIPTION
**Pull request by akssri**

### CODE REVIEW

**Comment by akssri** [comment]
I signed it!

**Comment by jch1** [comment]
Thanks @akssri - can you provide a more descriptive description of what's being fixed please?

**Comment by akssri** [comment]
Yes,
- ```im_begin``` gives the crop for the input image: axis-2 refers to channels (```num-channels```) (L672). 
- ```masks``` only has a single channel, with axis-0 indexing the bounding boxes (```num-instances```). (L628)
- Unless ```num-channels == num-instances```, this will result in a loud/silent error.

**Comment by jch1** [comment]
Thank you @akssri !!

**Pull request merged**
