### PR TITLE
Update download_and_convert_mnist.py for 1.0 and python3 compatibility

### PR DESCRIPTION
**Pull request by snnn**

### CODE REVIEW

**Comment by snnn** [comment]
Hi @sguada ,
After creating this pull request, I find this repo already has a "update-slim" branch, and a pull request (#1053) for it.    @nealwu 's  cl looks better than mine.  And python3 compatibility is another big issue, I didn't solve it well.

What do you think?

Thanks.

**Comment by nealwu** [comment]
@snnn, what does `'png'.encode()` help fix here? This is the part for Python 3 compatibility I'm assuming?

**Comment by snnn** [comment]
Yes. Because tf on windows only supports python 3, I have to make these compatibility changes.
There are a lot of places to be changed. Here are some of them.

	--- a/slim/datasets/dataset_utils.py
	+++ b/slim/datasets/dataset_utils.py
	@@ -125,7 +125,7 @@ def read_label_file(dataset_dir, filename=LABELS_FILENAME):
	   """
	   labels_filename = os.path.join(dataset_dir, filename)
	   with tf.gfile.Open(labels_filename, 'r') as f:
	-    lines = f.read().decode()
	+   lines = f.read()
	   lines = lines.split('\n')
	   lines = filter(None, lines)

	diff --git a/slim/datasets/download_and_convert_cifar10.py b/slim/datasets/download_and_convert_cifar10.py
	index 2cb787d..0284202 100644
	--- a/slim/datasets/download_and_convert_cifar10.py
	+++ b/slim/datasets/download_and_convert_cifar10.py
	@@ -26,7 +26,7 @@ from __future__ import absolute_import
	 from __future__ import division
	 from __future__ import print_function

	-import cPickle
	+import pickle as cPickle
	 import os
	 import sys
	 import tarfile
	@@ -72,14 +72,14 @@ def _add_to_tfrecord(filename, tfrecord_writer, offset=0):
	   Returns:
		 The new offset.
	   """
	-  with tf.gfile.Open(filename, 'r') as f:
	-    data = cPickle.load(f)
	+  with tf.gfile.Open(filename, 'rb') as f:
	+    data = cPickle.load(f, encoding='bytes')

	-  images = data['data']
	+  images = data[b'data']
	   num_images = images.shape[0]

	   images = images.reshape((num_images, 3, 32, 32))
	-  labels = data['labels']
	+  labels = data[b'labels']

	   with tf.Graph().as_default():
		 image_placeholder = tf.placeholder(dtype=tf.uint8)
	@@ -99,7 +99,7 @@ def _add_to_tfrecord(filename, tfrecord_writer, offset=0):
								   feed_dict={image_placeholder: image})

			 example = dataset_utils.image_to_tfexample(
	-            png_string, 'png', _IMAGE_SIZE, _IMAGE_SIZE, label)
	+            png_string, b'png', _IMAGE_SIZE, _IMAGE_SIZE, label)
			 tfrecord_writer.write(example.SerializeToString())

	   return offset + num_images
	diff --git a/slim/datasets/download_and_convert_mnist.py b/slim/datasets/download_and_convert_mnist.py
	index 28b2513..d6ae874 100644
	--- a/slim/datasets/download_and_convert_mnist.py
	+++ b/slim/datasets/download_and_convert_mnist.py
	@@ -125,7 +125,7 @@ def _add_to_tfrecord(data_filename, labels_filename, num_images,
			 png_string = sess.run(encoded_png, feed_dict={image: images[j]})

			 example = dataset_utils.image_to_tfexample(
	-            png_string, 'png', _IMAGE_SIZE, _IMAGE_SIZE, labels[j])
	+            png_string, 'png'.encode(), _IMAGE_SIZE, _IMAGE_SIZE, labels[j])
			 tfrecord_writer.write(example.SerializeToString())


	diff --git a/slim/eval_image_classifier.py b/slim/eval_image_classifier.py
	index f4d3f6a..43d8642 100644
	--- a/slim/eval_image_classifier.py
	+++ b/slim/eval_image_classifier.py
	@@ -158,7 +158,7 @@ def main(_):
		 })

		 # Print the summaries to screen.
	-    for name, value in names_to_values.iteritems():
	+    for name, value in names_to_values.items():
		   summary_name = 'eval/%s' % name
		   op = tf.summary.scalar(summary_name, value, collections=[])
		   op = tf.Print(op, [value], summary_name)
	@@ -183,7 +183,7 @@ def main(_):
			 checkpoint_path=checkpoint_path,
			 logdir=FLAGS.eval_dir,
			 num_evals=num_batches,
	-        eval_op=names_to_updates.values(),
	+        eval_op=list(names_to_updates.values()),
			 variables_to_restore=variables_to_restore)


	diff --git a/slim/nets/inception_v4.py b/slim/nets/inception_v4.py
	index b706d5b..154faf9 100644
	--- a/slim/nets/inception_v4.py
	+++ b/slim/nets/inception_v4.py
	@@ -223,7 +223,7 @@ def inception_v4_base(inputs, final_endpoint='Mixed_7d', scope=None):

		   # 35 x 35 x 384
		   # 4 x Inception-A blocks
	-      for idx in xrange(4):
	+      for idx in range(4):
			 block_scope = 'Mixed_5' + chr(ord('b') + idx)
			 net = block_inception_a(net, block_scope)
			 if add_and_check_final(block_scope, net): return net, end_points
	@@ -235,7 +235,7 @@ def inception_v4_base(inputs, final_endpoint='Mixed_7d', scope=None):

		   # 17 x 17 x 1024
		   # 7 x Inception-B blocks
	-      for idx in xrange(7):
	+      for idx in range(7):
			 block_scope = 'Mixed_6' + chr(ord('b') + idx)
			 net = block_inception_b(net, block_scope)
			 if add_and_check_final(block_scope, net): return net, end_points
	@@ -247,7 +247,7 @@ def inception_v4_base(inputs, final_endpoint='Mixed_7d', scope=None):

		   # 8 x 8 x 1536
		   # 3 x Inception-C blocks
	-      for idx in xrange(3):
	+      for idx in range(3):
			 block_scope = 'Mixed_7' + chr(ord('b') + idx)
			 net = block_inception_c(net, block_scope)
			 if add_and_check_final(block_scope, net): return net, end_points

I guess tf already has a guideline of how to write Python 2-3 compatible code. Please tell me where can I find it.  Thank you.

**Comment by nealwu** [comment]
Hi @snnn, I'm not aware of such a guide. All I was able to find for you was this: https://www.tensorflow.org/community/style_guide#python_2_and_3_compatible. In the meantime I can go ahead and merge this in.

**Pull request merged**
