### PR TITLE
applied fix for mnist data extraction helper function

### LINKED ISSUE #910: seek() takes exactly 2 arguments (3 given)
## Please let us know which model this issue is about (specify the top-level directory)
In the models/differential_privacy/multiple_teachers I have run this line:

python train_teachers.py --nb_teachers=100 --teacher_id=10 --dataset=mnist --max_steps=300

It ran but when I try and run this line or rerun the previous line:

python train_student.py --nb_teachers=100 --dataset=mnist --stdnt_share=5000

I get the error in the subject line.  If I delete the /tmp files I can rerun the first line again but I can't run the second line.  The problem (I think) is that that in input.py this function is called for both commands:

def extract_mnist_data(filename, num_images, image_size, pixel_depth):
  """
  Extract the images into a 4D tensor [image index, y, x, channels].

  Values are rescaled from [0, 255] down to [-0.5, 0.5].
  """
  # if not os.path.exists(file):
  if not tf.gfile.Exists(filename+".npy"):
    with gzip.open(filename) as bytestream:
      bytestream.read(16)
      buf = bytestream.read(image_size * image_size * num_images)
      data = np.frombuffer(buf, dtype=np.uint8).astype(np.float32)
      data = (data - (pixel_depth / 2.0)) / pixel_depth
      data = data.reshape(num_images, image_size, image_size, 1)
      np.save(filename, data)
      return data
  else:
    with tf.gfile.Open(filename+".npy", mode='r') as file_obj:
      return np.load(file_obj)

The first time I call train_teachers, the top part of the if runs.  When I call the train_students, the bottom part runs and blows up.

### PR DESCRIPTION
**Pull request by npapernot**
This small edit should close #910 

It replaces gfile with standard OS functions

### CODE REVIEW

**Comment by nealwu** [comment]
@panyx0718 could you take a quick look?

**Comment by nealwu** [comment]
Going to close this since it seems out of date -- there's a good chance it was fixed by 1.0 anyway. If the issue still exists, feel free to reopen or make a new pull request.

**Comment by harsimrans** [comment]
@nealwu  I tried out for tensorflow version 1.0. The issue still exists.

**Comment by harsimrans** [comment]
@nealwu Applying the same fix for "def extract_mnist_labels(filename, num_images)" as was done for "def extract_mnist_data(filename, num_images, image_size, pixel_depth)" did the task for me.

I've pasted the contents of the patch file.

diff --git a/differential_privacy/multiple_teachers/input.py b/differential_privacy/multiple_teachers/input.py
index e57da68..5908b8c 100644
--- a/differential_privacy/multiple_teachers/input.py
+++ b/differential_privacy/multiple_teachers/input.py
@@ -278,7 +278,8 @@ def extract_mnist_labels(filename, num_images):
   Extract the labels into a vector of int64 label IDs.
   """
   # if not os.path.exists(file):
-  if not tf.gfile.Exists(filename+".npy"):
+  # if not tf.gfile.Exists(filename+".npy"):
+  if not os.path.exists(filename+".npy"):
     with gzip.open(filename) as bytestream:
       bytestream.read(8)
       buf = bytestream.read(1 * num_images)
@@ -286,8 +287,11 @@ def extract_mnist_labels(filename, num_images):
       np.save(filename, labels)
     return labels
   else:
-    with tf.gfile.Open(filename+".npy", mode='r') as file_obj:
-      return np.load(file_obj)
+      # with tf.gfile.Open(filename+".npy", mode='r') as file_obj:
+      fo = open(filename+".npy", "rw+")
+      fo.close()
+      with open(filename+".npy", mode='r+') as file_obj:
+        return np.load(file_obj)
 
 
 def ld_svhn(extended=False, test_only=False):

**Pull request closed without merging**
