### PR TITLE
WIP: 2.0 Reference Models: Bert tpu with dist strat and keras

### PR DESCRIPTION
**Pull request by rok**
Should close [issue #26994](https://github.com/tensorflow/tensorflow/issues/26994) and [issue #26995](https://github.com/tensorflow/tensorflow/issues/26995).

### CODE REVIEW

**Comment by tfboyd** [comment]
We are about to move BERT under models/official with a TF 2.0 version (Keras without compat.v1) that works on both TPU and GPU. I did not test your code, it is a nice example of upgrading TF 1.0 code to 2.0 via the safest method possible.  compat.v1.

**Comment by rok** [comment]
@tfboyd thanks for the feedback.
Is there work being done on this internally? I don't want to duplicate work :).

**Comment by rachellj218** [comment]
Thank you, Rok. Yes, this is done internally. We are going to release the code to models/official in a week or so.

**Comment by rok** [comment]
Cool! I was wondering if that was happening. :)
Is there a way for you to mark open issues like that (e.g. [#26994](https://github.com/tensorflow/tensorflow/issues/26994), [#26995](https://github.com/tensorflow/tensorflow/issues/26995)) as assigned?

**Comment by tfboyd** [comment]
I assigned both of them to me and made a comment.  I really am sorry.  Did you have any issues with the upgrade script; that would be really useful to know.

**Comment by rok** [comment]
@tfboyd no worries, thanks for the clarification :).
The script worked nicely, maybe @icanswim has some comments?

**Pull request closed without merging**
