### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by lilipads**
update installation instrument for mac users

### CODE REVIEW

**Comment by lilipads** [comment]
I signed it!

**Comment by derekjchow** [comment]
Could you double check you signed the CLA?

**Comment by lilipads** [comment]
> Could you double check you signed the CLA?

Thank you for reviewing. I realized I signed with a different email address. I linked that email address on CLA to my github and also added my github account name on the CLA.

**Comment by lilipads** [comment]
> Could you double check you signed the CLA?

@derekjchow  Looks like all checks are passed. Would you help merge the pull request? Thank you!

**Comment by derekjchow** [comment]
Sorry for the delay and thanks for the patch!

**Pull request merged**
