### PR TITLE
Fixes broken visualization in Perspective Transformer Nets, #2197

### PR DESCRIPTION
**Pull request by mees**
Fixes broken visualization in Perspective Transformer Nets, bug #2197.

### CODE REVIEW

**Comment by mees** [comment]
@xcyan @arkanath,  this is the fix I found for the colorization of the 3D shapes.

**Comment by xcyan** [comment]
Did you test on both linux and mac?

**Comment by mees** [comment]
just on Ubuntu, I don't have a mac. But it anyway complained that the api
changed for marching cubes. It recommended either switching
to marching_cubes_lewiner or  marching_cubes_classic.

**Comment by arkanath** [comment]
Can you link the documentation which states that the API call already being used is deprecated?

**Comment by mees** [comment]
@arkanath With marching_cubes I get the following error when running the perspective transformer:
/home/meeso/.virtualenvs/2d_to_3d/local/lib/python2.7/site-packages/skimage/measure/_marching_cubes_lewiner.py:167: skimage_deprecation: `marching_cubes` now uses a better and faster algorithm, and returns four instead of two outputs (see docstring for details). Backwards compatibility with 0.12 and prior is available with `marching_cubes_classic`. This function will be removed in 0.14, consider switching to `marching_cubes_lewiner`.
You have that warning here: https://github.com/scikit-image/scikit-image/blob/v0.13.x/skimage/measure/_marching_cubes_lewiner.py#L167

And here is the API change: https://github.com/scikit-image/scikit-image/blob/37ed59d2880fa96ff908608d7f723b98cd319c9b/doc/source/api_changes.rst (skimage.measure.marching_cubes has been removed in favor of skimage.measure.marching_cubes_lewiner.)

**Comment by xcyan** [comment]
Looks good to me. Maybe it is better to mention the version of scikit-image library you are using in README.

**Comment by xcyan** [comment]
@hellojas Can you merge this PR? Thanks!

**Pull request merged**
