### PR TITLE
bug correction for dataset import

### PR DESCRIPTION
**Pull request by jind11**
The iterator to generate batches for imported dataset is missed.

### CODE REVIEW

**Comment by jind11** [comment]
hi, I have signed the CLA. Thanks!

**Comment by jind11** [comment]
I submitted another GLA using my email used for github

**Comment by jind11** [comment]
hi, I have resolved this problem

**Comment by jind11** [comment]
I signed it!

**Comment by karmel** [comment]
Thanks, @jind11 . The current best-practice is to return the dataset directly from the input_fn. That is reflected in the [Dataset performance guide](https://www.tensorflow.org/versions/master/performance/datasets_performance), though I note it is not yet in the [Dataset Quickstart](https://www.tensorflow.org/versions/master/get_started/datasets_quickstart) -- @MarkDaoust , do we plan on updating the sample input_fn in the Dataset docs?

**Comment by jind11** [comment]
I tried running the cifar10_main.py but got an error on the input_fn, so I added these several lines to fix the bug.

**Comment by MarkDaoust** [comment]
> Dataset Quickstart

@karmel  - Thanks for pointing that out I've drafted some clarifications for this section.

@jind11 - Thanks for the PR (the best kind of bug report is one with a fix attached), but in this case the functionality is new in TensorFlow r1.5 I bet you're on an older version try a `pip install --upgrade tensorflow` and it should work without the change.

**Comment by jind11** [comment]
@MarkDaoust I see. Yeah, I am now using tensorflow 1.4. So it would be great that you can clarify this version requirement in the readme page so that we know what could cause the error when we run the code. Thanks a lot for your help!

**Comment by karmel** [comment]
Thanks, @jind11 and @MarkDaoust . I will close this given the successful resolution. Version recommendations for all of the official models can be found here: https://github.com/tensorflow/models/tree/master/official#tensorflow-official-models

**Pull request closed without merging**
