### PR TITLE
Cog_Map: Resolve 11 undefined names that could raise NameError at runtime

### PR DESCRIPTION
**Pull request by cclauss**
flake8 testing of https://github.com/tensorflow/models on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__

```
./cognitive_mapping_and_planning/cfgs/config_distill.py:94:33: F821 undefined name 'resnet_v2_50_path'
  args.solver.pretrained_path = resnet_v2_50_path
                                ^

./cognitive_mapping_and_planning/src/depth_utils.py:26:19: F821 undefined name 'utils'
  camera_matrix = utils.Foo(xc=xc, zc=zc, f=f)
                  ^

./cognitive_mapping_and_planning/src/file_utils.py:36:14: F821 undefined name 'file_name'
  with fopen(file_name, 'r') as f:
             ^

./cognitive_mapping_and_planning/src/file_utils.py:38:10: F821 undefined name 'np'
    II = np.array(I)
         ^

./cognitive_mapping_and_planning/src/graph_utils.py:453:7: F821 undefined name 'logging'
      logging.error('Did not find any good nodes.')
      ^

./cognitive_mapping_and_planning/src/graph_utils.py:468:14: F821 undefined name 'get_path_ids'
      path = get_path_ids(start_node_ids[i], end_node_ids[i], pred_map)
             ^

./cognitive_mapping_and_planning/src/graph_utils.py:511:7: F821 undefined name 'logging'
      logging.error('Did not find any good nodes.')
      ^

./cognitive_mapping_and_planning/src/graph_utils.py:517:14: F821 undefined name 'get_path_ids'
      path = get_path_ids(start_node_ids[i], end_node_ids[i], pred_map)
             ^

./cognitive_mapping_and_planning/src/graph_utils.py:547:14: F821 undefined name 'get_path_ids'
      path = get_path_ids(start_node_ids[i], end_node_ids[i], pred_map)
             ^

./cognitive_mapping_and_planning/src/map_utils.py:143:7: F821 undefined name 'logging'
      logging.error('Unknown resizing method')
      ^

./cognitive_mapping_and_planning/tfcode/vision_baseline_lstm.py:152:21: F821 undefined name 'is_training'
        is_training=is_training)
                    ^
```

### CODE REVIEW

**Comment by derekjchow** [comment]
The object_detection changes look good to me. If you can separate them into another PR, I can merge them.

**Comment by cclauss** [comment]
@s-gupta Can you please look at the cognitive_mapping_and_planning/src changes?

**Comment by s-gupta** [comment]
These look good to me. Thanks for all the fixes!

**Comment by cclauss** [comment]
@s-gupta nudge

**Comment by s-gupta** [comment]
Sorry for the late reply. Line 32 does `import matplotlib.pyplot as plt` and should be deleted as it is now being done on line 50 after `matplotlib.use("Agg")`. Thanks!

**Comment by s-gupta** [comment]
Thanks! Looks good to me.

**Comment by cclauss** [comment]
@s-gupta I am unsure of the process here.  Are you the maintainer of cognitive mapping and planning or does someone else need to merge this?

**Comment by s-gupta** [comment]
I wrote this code and prepared the pull request to merge it but I dont have write permission to this repository. Someone from Google merges is I believe.

**Comment by cclauss** [comment]
Yes.  That is the sense that I got.  Thanks for your guidance.

**Pull request closed without merging**
