### PR TITLE
update to tf2.0 for deep_speech, by tf_upgrade_v2

### PR DESCRIPTION
**Pull request by moneypi**
1. update to tf2.0 for deep_speech, by tf_upgrade_v2
2. compatible with tf1.15

### CODE REVIEW

**Comment by saberkun** [comment]
The PR looks good. Could you resolve the conflicts? We can merge it.

**Comment by moneypi** [comment]
> Please fix conflicts.

**Comment by moneypi** [comment]
> Please fix conflicts.
Hello, I will commit a new PR to replace this one.

**Comment by moneypi** [comment]
> Please fix conflicts.

Hello, I will commit a new PR to replace this one.

**Comment by moneypi** [comment]
> Please fix conflicts.

Hello, new PR is here
https://github.com/tensorflow/models/pull/8696/commits/5df7aedf7ded4ebd51d7849523f216fd718c70f8

**Pull request closed without merging**
