### PR TITLE
Update mobilenet_example.ipynb

### PR DESCRIPTION
**Pull request by okdshin**

### CODE REVIEW

**Comment by okdshin** [comment]
I signed it!

**Comment by sguada** [comment]
Can you provide a description for this PR, could you explain why this change is necessary?

**Comment by okdshin** [comment]
It occurs an error as `base_name` is not defined. `checkpoint_name` is defined, but it is not used later. I can run it by replacing `checkpoint_name` with `base_name`.

**Comment by marksandler2** [comment]
I think this got fixed in the head. Thank you for your pull request.

**Pull request closed without merging**
