### PR TITLE
Updated the cifar10 model to be compatible with the latest version of TensorFlow

### PR DESCRIPTION
**Pull request by nealwu**

### CODE REVIEW

**Comment by nealwu** [comment]
@annarev, when should we update `tf.concat_v2` here to just `tf.concat`?

**Comment by wookayin** [comment]
Just question: Is`tf.contrib.deprecated.XXX_summary` preferred over the new `tf.summary.XXX`?

**Comment by nealwu** [comment]
@wookayin I believe it may provide more compatibility at the moment. @gunan might know better?

**Comment by annarev** [comment]
@nealwu, you can update tf.concat_v2 --> tf.concat any time. it is in the v1.0.0-rc0 release

**Comment by nealwu** [comment]
@annarev OK, will do.

**Comment by nealwu** [comment]
@JavidPack Thanks for pointing this out. Going to update these calls to the newest version.

**Pull request merged**
