### PR TITLE
Fix TensorRT test output and add int8 result.

### PR DESCRIPTION
**Pull request by aaroey**

### CODE REVIEW

**Comment by aaroey** [comment]
Hi @karmel,

I get the result by running the script on my local machine with a Quadro P5000, so the numbers (images/sec) are much smaller comparing to the original. Just FYI.

Thanks. :)

**Comment by aaroey** [comment]
Also @samikama.

**Comment by samikama** [comment]
Under ideal circumstances, calibration needs to be done on a few batches of realistic data. For this script same input is used for calibration so 2 or 3 calibration loops should be enough. Though using input image as calibration image does not mean that the results will be perfect.

**Comment by samikama** [comment]
@karmel, the log from  @aaroey  is from P5000, which is not efficient in FP16 so probably running FP32 instead. I can try to update the numbers if you want.

**Comment by karmel** [comment]
That would be great-- thanks.

**Comment by samikama** [comment]
@karmel Here is the list from my machine. 
> 
> ==========================
> network: native_resnetv2_imagenet_frozen_graph.pb,	 batchsize 128, steps 3
>   fps 	median: 930.2, 	mean: 934.9, 	uncertainty: 5.9, 	jitter: 3.3
>   latency 	median: 0.13760, 	mean: 0.13692, 	99th_p: 0.13793, 	99th_uncertainty: 0.00271
> 
> ==========================
> network: tftrt_fp32_resnetv2_imagenet_frozen_graph.pb,	 batchsize 128, steps 3
>   fps 	median: 1160.2, 	mean: 1171.8, 	uncertainty: 18.0, 	jitter: 17.8
>   latency 	median: 0.11033, 	mean: 0.10928, 	99th_p: 0.11146, 	99th_uncertainty: 0.00110
> 
> ==========================
> network: tftrt_fp16_resnetv2_imagenet_frozen_graph.pb,	 batchsize 128, steps 3
>   fps 	median: 2007.2, 	mean: 2007.4, 	uncertainty: 0.4, 	jitter: 0.7
>   latency 	median: 0.06377, 	mean: 0.06376, 	99th_p: 0.06378, 	99th_uncertainty: 0.00001
> 
> ==========================
> network: tftrt_int8_resnetv2_imagenet_frozen_graph.pb,	 batchsize 128, steps 3
>   fps 	median: 2970.2, 	mean: 2971.4, 	uncertainty: 109.8, 	jitter: 279.4
>   latency 	median: 0.04309, 	mean: 0.04320, 	99th_p: 0.04595, 	99th_uncertainty: 0.00286
>

**Pull request merged**
