### PR TITLE
Update pylint.rcfile

### PR DESCRIPTION
**Pull request by saberkun**

### CODE REVIEW

**Comment by tfboyd** [comment]
@guptapriya   This seems fine with me and I am guessing this might make it better match internal.

**Comment by tfboyd** [comment]
Your change triggers a lot more lint issues.  Good/Bad  I don't know.  FYI: I am totally fine if we need to spend a couple hours powering through lint issues to line up with a new set of "rules".

**Comment by guptapriya** [comment]
+1 to Toby, some description would be nice. Is this copied from somewhrre else, what rules are we  trying to follow?

**Comment by saberkun** [comment]
Sorry. This is experimental and I should drop it. In fact, the previous
lintrc disabled many important things. Will try a few other improvements.

**Pull request closed without merging**
