### PR TITLE
[ResNet] Removed tests no longer closely monitored.

### PR DESCRIPTION
**Pull request by tfboyd**
These tests are not monitored closely.  In realty all the "graph" tests should also be removed; but I need a few more days to think about them.

### CODE REVIEW

**Comment by saberkun** [comment]
Copybara service setup might work now. 
I am testing a change internally and see if it can get out. Please wait a bit. Thanks

**Comment by tfboyd** [comment]
No rush I am not touching anything.  :-)

**Comment by saberkun** [comment]
Sorry need some debugging. Please hold.

**Comment by tfboyd** [comment]
Take as long as you need; this is not a big deal.  Just cleanup while I am thinking about it.

**Comment by saberkun** [comment]
I think I fixed one bug. Going to test github to piper again.

**Pull request merged**
