### PR TITLE
Update GraphKeys.VARIABLES to GraphKeys.GLOBAL_VARIABLES. and Update ones_initializer to ones_initializer()

### PR DESCRIPTION
**Pull request by laosiaudi**
1. Thanks for @cshallue 's [solution](https://github.com/tensorflow/models/commit/946c75e5b531691e40905e86c5a937052e2a6596) for im2txt to fix the global_step uninitialized error in distributed mode.
2. In inception model, change ones_intializer to ones_initializer() to fit the new tensorflow python API.

### CODE REVIEW

**Comment by laosiaudi** [comment]
@googlebot I signed it!

**Comment by laosiaudi** [comment]
@googlebot I signed the cla with another email address, but I can't add the email for my github account to that email address, could you please help with that? Thanks.

**Comment by laosiaudi** [comment]
@googlebot I signed it!

**Comment by nealwu** [comment]
Closing because it looks like these changes have already been made. Thanks for bringing this to my attention though -- there are a few other instances of `tf.GraphKeys.VARIABLES` in this repository, so I'll submit a new PR to update those.

**Comment by nealwu** [comment]
https://github.com/tensorflow/models/pull/1184

**Pull request closed without merging**
