### PR TITLE
colab and local

### PR DESCRIPTION
**Pull request by AshishGusain17**
need to work on colab or locally, get these notebooks into implementation

### CODE REVIEW

**Comment by AshishGusain17** [comment]
> @googlebot I signed it!

**Comment by AshishGusain17** [comment]
> @googlebot I fixed it.

**Comment by jaeyounkim** [comment]
Please sign the CLA, and provide more details about your PR.

**Comment by AshishGusain17** [comment]
I have signed multiple number of times.

**Comment by jaeyounkim** [comment]
@AshishGusain17 I have confirmed that you signed the CLA. Thank you!

**Comment by jaeyounkim** [comment]
Please submit a pull request with detailed description.

**Pull request closed without merging**
