### PR TITLE
Update docker_test.sh to use 1.4 docker images.

### PR DESCRIPTION
**Pull request by case540**

### CODE REVIEW

**Comment by av8ramit** [comment]
Jenkins, test this please.

**Comment by av8ramit** [comment]
@nealwu is it okay to merge this? I understand models isn't officially moving to 1.4 yet?

**Comment by nealwu** [comment]
Let's hold off on this until TensorFlow 1.4 is the official version. We want to make sure the models are always tested with the latest official release.

**Comment by av8ramit** [comment]
Closing! @case540 please update the doc to only do this after official releases.

**Pull request closed without merging**
