### PR TITLE
Differential privacy with multiple teachers

### PR DESCRIPTION
**Pull request by goodfeli**
This PR is related to @npapernot 's intern project. It should be reviewed by Ulfar Erlingsson (not sure of github username).

This PR contains one configuration of MNIST student training.

### CODE REVIEW

**Comment by goodfeli** [comment]
I signed it

**Comment by drpngx** [comment]
You need an exclamation point AFAIK ("I signed it!")

**Comment by goodfeli** [comment]
I signed it!

**Comment by goodfeli** [comment]
(It would be better for @googlebot  say that the reply must be verbatim "I signed it!" rather than to say "e.g.", implying that there are many things one could say)

**Comment by drpngx** [comment]
That is strage, could you visit the URL again? Not sure why the bot isn't picking it up. Perhaps try again.

**Comment by benoitsteiner** [comment]
Jenkins, test this please.

**Comment by nealwu** [comment]
@goodfeli is this a change we still want?

**Comment by npapernot** [comment]
This was replaced by #655

**Pull request closed without merging**
