### PR TITLE
improved ArcStandardTransitionSystem.PerformRightArc()

### PR DESCRIPTION
**Pull request by chantera**
This is more efficient implementation for PerformRightArc().

### CODE REVIEW

**Comment by chantera** [comment]
I signed it!

**Comment by nealwu** [comment]
Tagging @googlebot in case it hasn't refreshed this PR.

**Comment by nealwu** [comment]
@googlebot

**Comment by nealwu** [comment]
@chantera could you sign the CLA? We'll need that before we can merge your PR.

**Comment by chantera** [comment]
I signed it!

**Pull request merged**
