### PR TITLE
import name 'profiler_v2' solved

### PR DESCRIPTION
**Pull request by ayushmankumar7**
Issue: #8246

Current Results: 
Screenshot from 2020-03-05 18-07-15

### CODE REVIEW

**Comment by saberkun** [comment]
Hi, the code was updated for tf-nightly/tf 2.2.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/profiler/profiler_v2.py
It is probably not the right way to directly import tensorflow internal modules.
Would you try tf.profiler.experimental.Profile? Also, the code should be good with TF nightly.

**Comment by ayushmankumar7** [comment]
I'm currently using TF2.1.0. Maybe it's not the right way to do the thing. I just tried changing profiler_v2 to profiler and it solved the problem.

**Comment by saberkun** [comment]
I see. It is good to keep this in your local change. TF 2.2 is coming and our code mostly is based on the latest TF under development. Sorry for inconvenience

**Comment by ayushmankumar7** [comment]
Not a Problem. Excited for the new update.

**Pull request closed without merging**
