### PR TITLE
CogMap tfcode: Fix undefined name 'is_training'

### PR DESCRIPTION
**Pull request by cclauss**
First reported in  #1981 ...

__is_training__ is an undefined name [inside the function __visit_count_fc()__](https://github.com/tensorflow/models/blob/master/research/cognitive_mapping_and_planning/tfcode/vision_baseline_lstm.py#L135-L153) because the function takes 5 parameters and none of them is called __is_training__.  Undefined names might raise NameError at runtime.

flake8 testing of https://github.com/tensorflow/models

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./research/cognitive_mapping_and_planning/tfcode/vision_baseline_lstm.py:152:21: F821 undefined name 'is_training'
        is_training=is_training)
                    ^
```

In the tensorflow/models repo, there is [only one caller](visit_count_fc) of the function __visit_count_fc()__ and that caller passes 6 parameters and the last one is called __is_training__.

The proposed fix is to add __is_training__ as the sixth parameter of __visit_count_fc()__ to match both the caller and the internals of the function and thereby eliminate the undefined name.

### CODE REVIEW

**Comment by cclauss** [comment]
@nealwu @karmel Could we please get a reviewer assigned?  Any comments on https://github.com/tensorflow/models/pulls/cclauss

**Comment by karmel** [comment]
Thanks, @cclauss . Research models are the responsibility of the individual researchers listed in [the owners file](/tensorflow/models/tree/master/CODEOWNERS). For small changes like this, I can do my best, but can you provide evidence that you have run the models and they perform/converge as expected? Otherwise, I leave to @s-gupta to review as owner.

**Comment by cclauss** [comment]
@s-gupta Can we please get your review on these changes?

**Comment by cclauss** [comment]
__bump__ on this PR.

**Comment by cclauss** [comment]
@karmel Is there an owner that [has the commit bit](https://github.com/tensorflow/models/pull/1981#issuecomment-328090592) that can review this one?

**Comment by karmel** [comment]
@cclauss If you can confirm that the model still runs as intended, I can merge, and @s-gupta or others can create new issues to roll back if necessary. But, please run the model to confirm that it still works.

**Pull request closed without merging**
