### PR TITLE
Change key of type 'tuple' to 'str'

### PR DESCRIPTION
**Pull request by justanhduc**
dictionary having both 'tuple' and 'str' keys cannot be 'sorted'

### CODE REVIEW

**Comment by derekjchow** [comment]
LGTM

**Comment by justanhduc** [comment]
@jch1 I updated the PR according to your comment. Please have a look!

**Comment by derekjchow** [comment]
@justanhduc could you resolve the remaining merge conflicts?

**Comment by justanhduc** [comment]
@derekjchow I resolved all the conflicts.

**Comment by derekjchow** [comment]
Thanks for the PR Justan!

**Pull request merged**
