### PR TITLE
Fixed improper HNASNet architecture

### PR DESCRIPTION
**Pull request by adrianboguszewski**
Fixes https://github.com/tensorflow/models/issues/6393

### CODE REVIEW

**Comment by aquariusjay** [comment]
Looks great!
Thank you, adrianboguszew!
Just want to double check with you.
Have you trained the code for some longer time and run eval/vis as well?

Thanks,

**Comment by adrianboguszewski** [comment]
Yes. There is no exception after a few hours training. 
Eval checked also. Works.

**Comment by NathanielNguyen11** [comment]
Dear Mr Adrian,
Will you give us the command to reproduce? Because, again I have your previous problem.
Thank you very much.

**Comment by adrianboguszewski** [comment]
@NathanielNguyen11 
Look at #6393

**Pull request merged**
