### PR TITLE
Refactored ResNet code and added additional architectures.

### PR DESCRIPTION
**Pull request by vighneshbirodkar**

### CODE REVIEW

**Comment by vighneshbirodkar** [comment]
@tfboyd Any updates on this ?

**Comment by tfboyd** [comment]
Perf slowed me down.  Should get reviewed this week?  An ahead of time
thing.  I suggest a class default of 10.  That is the default cifar dataset
we use and will avoid awkward issues.  If you can have good layer names for
small models that is good enough.  As long as the solution to naming is
what you might suggest to someone it should be fine

**Comment by tfboyd** [comment]
@yuefengz   Can you give a quick look?  I want to make sure I am not missing anything.

**Comment by robieta** [comment]
It's totally stylistic, but one thing I would recommend is using functools.partial to cut down on a lot of the boilerplate and naming the functions like classes (since they're going to give you a Model at the end). So at the bottom you would just have:
```
ResNet20 = functools.partial(resnet, num_blocks=3)
ResNet32 = functools.partial(resnet, num_blocks=5)
...
```

Thanks for making this more concise.

**Comment by yuefengz** [comment]
The refactoring for resnet56 looks good to me.

**Comment by vighneshbirodkar** [comment]
@tfboyd Done . Apologies for the delay

**Comment by vighneshbirodkar** [comment]
Hey @tfboyd , @robieta Are there any more changes you would like me to do ?

**Comment by tfboyd** [comment]
Sorry I got distracted.  Trying to kick off a test now.

**Comment by tfboyd** [comment]
Logs of running tests, when finished we can LGTM and merge.
1 GPU Keras
https://sponge.corp.google.com/bfe6b84d-56f9-481a-ab6d-37de767328fc
2 GPU Keras
https://sponge.corp.google.com/bbcec6ef-c00c-4689-a686-ec9e9c5bec13

**Comment by vighneshbirodkar** [comment]
@tfboyd The tests are passing.

**Pull request merged**
