### PR TITLE
Slim walkthough notebook update to show difference of inference for models with 1000 and 1001 classes.

### PR DESCRIPTION
**Pull request by warmspringwinds**
A small update that makes it easier for end-users to understand the difference of how to
make inference with models that were trained using 1000 classes and 1001 classes on imagenet.

I faced this problem when I plugged-in VGG-19 model into Inception v1 code and got wrong predictions
because of the shift in class names.
https://github.com/tensorflow/tensorflow/issues/5228

The pull request adds example of evaluation of VGG-19 with correct name shift.

### CODE REVIEW

**Comment by warmspringwinds** [comment]
I signed it!

**Comment by sguada** [comment]
For efficiency reasons and also because VGG-16 performs as well as VGG-19, can you use VGG-16 instead?

**Comment by warmspringwinds** [comment]
@sguada Did it :)

If you are interested, I can also add some parts from [here](http://warmspringwinds.github.io/tensorflow/tf-slim/2016/10/30/image-classification-and-segmentation-using-tensorflow-and-tf-slim/).

**Comment by warmspringwinds** [comment]
@sguada Do you want me to add something else or update ?

**Pull request merged**
