### PR TITLE
Bugfix for missing function rotator_metrics in models/ptn

### PR DESCRIPTION
**Pull request by xcyan**
This PR fixes the known bug when evaluating the rotator model in models/ptn. #2240 

Please check this out @arkanath @mees

### CODE REVIEW

**Comment by xcyan** [comment]
I signed it!

**Comment by mees** [comment]
thanks @xcyan, the patch works in general. However, you also need to fix a small detail in eval_rotator.py to enable the script to run. You need to change gs.DEFINE_string('master', 'local', '') to gs.DEFINE_string('master', '', '') to avoid a session error. Last question: the rnn1-rnn24 represent the error when predicting directly from input to 15 degrees*rotation_step or do you chain the (rotation) predictions?

**Comment by xcyan** [comment]
I think we accumulated the loss across rotations steps (actually average over the first K steps).
https://github.com/tensorflow/models/blob/master/ptn/losses.py#L49

**Comment by xcyan** [comment]
@mees Please close the issue if the problem has been resolved. Thank you!

**Comment by mees** [comment]
@xcyan @reedwm please add the fix flags.DEFINE_string('master', '', '') in eval_rotator.py . I didn't want to open a bug issue and create a PR, because I was hoping @xcyan could add this minor change before merging the whole patch.

**Pull request merged**
